added features page
Ajay-Dhangar/algo pull request #1004
Opened 2024-10-19 12:03 UTC by AswaniBolisetti

@ajay-dhangar 
I have features page and by clicking each feature that respective page will be opened
Kindly check it out

Could you please consider it as level 3 if you like it

https://github.com/user-attachments/assets/d9cea6e8-313c-4370-85f0-6a5bfd7e68b2

2024-10-19 17:06 UTC, ajay-dhangar commented
![{24815E48-942F-4F9A-AF98-386E3D5275B5}](https://github.com/user-attachments/assets/42e1e53b-2771-44c9-b279-6dfe25aa1673)

2024-10-19 17:08 UTC, AswaniBolisetti commented
@ajay-dhangar 
Actually I tried to solve them but i couldn't

2024-10-19 17:09 UTC, ajay-dhangar requested changes
don't install any packages

2024-10-19 17:09 UTC, ajay-dhangar commented on package.json
> +    "react-router-dom": "^5.3.4",
No need `"react-router-dom"` because we have already setup

2024-10-20 08:16 UTC, ajay-dhangar commented
I can close this issue today. However, we should not make this feature too complex. We need to maintain the codebase.

2024-10-20 08:16 UTC, closed without merging