added privacy policy page
Ajay-Dhangar/algo pull request #1007
Opened 2024-10-19 12:33 UTC by AswaniBolisetti

@ajay-dhangar 
I have added a page for privacy policy
kindly check it out

https://github.com/user-attachments/assets/8a0b94da-1289-4890-a162-5d1b25a6904d

2024-10-19 17:04 UTC, ajay-dhangar requested changes
change email based on suggestions

2024-10-19 17:04 UTC, ajay-dhangar commented on src/pages/privacy/index.tsx
> +            If you have any questions or concerns regarding this Privacy Policy, feel free to contact us at <a href="mailto:support@algowebsite.com" className="text-blue-600 dark:text-yellow-400">sup
replace `support@algowebsite.com` with `ajaydhangar49@gmail.com `

2024-10-19 17:36 UTC, AswaniBolisetti commented
@ajay-dhangar 
Could you please confirm whether email changed or not

2024-10-20 08:13 UTC, ajay-dhangar commented
> @ajay-dhangar Could you please confirm whether email changed or not

You need to push the code to this branch. Once the code is moved, I can then merge the changes.

2024-10-22 17:45 UTC, AswaniBolisetti commented
@ajay-dhangar 
Kindly review and merge it 
Please

2024-10-23 08:53 UTC, closed without merging

2024-10-24 14:58 UTC, AswaniBolisetti commented
@ajay-dhangar 
Could you please tell me why it was closed