java well know problem -Palindrome number and string.
Ajay-Dhangar/algo pull request #1035
Opened 2024-10-19 17:40 UTC by PradeepFSTdhane123

## 📥 Pull Request

### Description
palindrome problem string and number added.

Fixes # 805

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-20 03:10 UTC, ajay-dhangar requested changes
Please read our contributions guideline carefully. We have provided all of our resources, such as `.md` or `.mdx` syntax, our documentation format, and much more.

2024-10-20 04:35 UTC, PradeepFSTdhane123 commented
@ajay-dhangar I am also created fine in  .md  format , whart is the actual reason can you tell? so That I will improve it

2024-10-20 04:43 UTC, PradeepFSTdhane123 commented
my file format is .md so what is the issue for not mearching

On Sun, 20 Oct 2024 at 08:41, Ajay Dhangar ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please read our contributions guideline carefully. We have provided all of
> our resources, such as .md or .mdx syntax, our documentation format, and
> much more.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ajay-dhangar/algo/pull/1035#pullrequestreview-2379964801>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEUVCSN6DRAFOZBZM3CUZH3Z4MNMJAVCNFSM6AAAAABQHVUSYGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZZHE3DIOBQGE>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-10-20 08:06 UTC, ajay-dhangar requested changes
change your code based on suggestions

2024-10-20 08:06 UTC, ajay-dhangar commented on java/Palindrome_number.md
> +
can you write this in good way

2024-10-20 08:06 UTC, ajay-dhangar commented on java/Palindrome_number.md
> +
Write your code example like 

````md
```java
// your code here
```
````

2024-10-20 08:06 UTC, ajay-dhangar commented on java/Palindrome_string.md
> +
same mistake

2024-10-20 08:06 UTC, ajay-dhangar commented on java/Palindrome_string.md
> +
text is not looking good  why you use `//`

2024-10-22 02:09 UTC, closed without merging

2024-10-22 02:29 UTC, PradeepFSTdhane123 commented
@ajay-dhangar  solve the conflict kindely merge it