Add Documentation for Adding Two Numbers Represented as Linked Lists
Ajay-Dhangar/algo pull request #1076
Opened 2024-10-20 14:55 UTC by riyaa060

## 📥 Pull Request

### Description
This PR adds comprehensive documentation explaining the solution to the problem of adding two numbers represented as linked lists. 
Fixes #1064

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-22 03:47 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-22 03:47 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Add_two_number_as_LL.md
> +sidebar_label:  "Adding Two Numbers Represented as Linked Lists"
write in sort word for our sidebar

2024-10-22 03:47 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Delete_occurences_of_key.md
> +sidebar_label: "Deleting All Occurrences of a Key in a Doubly Linked List
write in sort word for our sidebar

2024-10-22 03:47 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Delete_occurences_of_key.md
> +---
can not read a block mapping entry; a multiline key may not be an implicit key.
like:
`name: null,`

2024-10-29 12:04 UTC, riyaa060 commented
Check @ajay-dhangar

2024-10-30 14:09 UTC, ajay-dhangar approved these changes
Done

2024-10-30 14:09 UTC, merged