Create Convolutional_Neural_Network.md
Ajay-Dhangar/algo pull request #1137
Opened 2024-10-21 15:08 UTC by inkerton

## 📥 Pull Request

### Description
Convolutional Neural Networks (CNNs) are a class of deep neural networks specifically designed to process data with a grid-like structure, such as images. CNNs are highly effective in tasks like image classification, object detection, and recognition due to their ability to capture spatial hierarchies in data through convolutional layers.

Fixes # (issue number) #1114 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-22 15:35 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-22 15:35 UTC, ajay-dhangar commented on docs/machine-learning/Convolutional_Neural_Network.md
> +  The time complexity depends on the number of filters, kernel size, and input dimensions. For an image of size \( n \times n \) with \( k \) filters of size \( f \times f \), the time complexity of
replace `\( n \times n \)` with `$ n \times n $`, `\( k \)` with `$k$`, `\( f \times f \)` with `$ f \times f $, and `\( O(n^2 \cdot f^2 \cdot k) \)` with `$ O(n^2 \cdot f^2 \cdot k)$`

2024-10-22 16:12 UTC, inkerton commented
done

2024-10-23 09:21 UTC, ajay-dhangar approved these changes
Done

2024-10-23 09:21 UTC, merged