Create Recurrent_Neural_Network.md
Ajay-Dhangar/algo pull request #1138
Opened 2024-10-21 15:13 UTC by inkerton

## 📥 Pull Request

### Description
Recurrent Neural Networks (RNNs) are a class of artificial neural networks designed for modeling sequential data by introducing loops that allow information to persist across time steps. They are widely used for tasks like time-series forecasting, natural language processing (NLP), and speech recognition because of their ability to process and maintain information from previous inputs.

Fixes # (issue number) #1115 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-22 15:40 UTC, ajay-dhangar requested changes
update code based on suggestions

2024-10-22 15:40 UTC, ajay-dhangar commented on docs/machine-learning/Recurrent_Neural_Network.md
> +
replace `\( T \)` with `$T$`, `\( n \)`, with `$n$`, `\( h \)` with `$h$`, and `\( O(T \cdot n \cdot h^2) \)` with `$ O(T \cdot n \cdot h^2) $`

2024-10-22 15:40 UTC, ajay-dhangar commented on docs/machine-learning/Recurrent_Neural_Network.md
> +
and also, replace with `$` with mathematical formula using LaTeX

2024-10-22 16:11 UTC, inkerton commented
done

2024-10-23 09:22 UTC, ajay-dhangar approved these changes
Done

2024-10-23 09:23 UTC, merged