Create Generative_Adversarial_Networks.md
Ajay-Dhangar/algo pull request #1140
Opened 2024-10-21 15:23 UTC by inkerton

## 📥 Pull Request

### Description
Generative Adversarial Networks (GANs) are a class of deep learning models designed to generate new data samples that are similar to a given dataset. GANs consist of two neural networks, the generator and the discriminator, which are trained simultaneously in a game-theoretic setting. The generator learns to produce realistic data, while the discriminator tries to distinguish between real and generated data. This adversarial process helps the generator improve over time.

Fixes #1117 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-22 15:51 UTC, ajay-dhangar requested changes
uses LaTeX equations with `$`

2024-10-22 16:06 UTC, inkerton commented
done

2024-10-23 09:27 UTC, ajay-dhangar requested changes
update your code

2024-10-23 09:27 UTC, ajay-dhangar commented on docs/machine-learning/Generative_Adversarial_Networks.md
> +   - Output: Synthetic data (e.g., an image).
use `$` for `\( z \sim N(0, 1) \))`

2024-10-23 09:27 UTC, ajay-dhangar commented on docs/machine-learning/Generative_Adversarial_Networks.md
> +The objective function for GANs is a **minimax game** where the generator \( G \) tries to minimize the loss, and the discriminator \( D \) tries to maximize it. This is given by:
use `$`

2024-10-23 16:18 UTC, inkerton commented on docs/machine-learning/Generative_Adversarial_Networks.md
> +The objective function for GANs is a **minimax game** where the generator \( G \) tries to minimize the loss, and the discriminator \( D \) tries to maximize it. This is given by:
Done

2024-10-25 11:58 UTC, ajay-dhangar approved these changes
Done

2024-10-25 11:58 UTC, merged