Github actions for more connectivity!
Ajay-Dhangar/algo pull request #1167
Opened 2024-10-22 01:56 UTC by smog-root

Closes #1088 

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @ajay-dhangar 

**Proof**:

**Issue open and close:**

![Screenshot 2024-10-21 152058](https://github.com/user-attachments/assets/2ed26727-c5d8-4320-b4e0-9e4ccaacac32)
<br>

**PR raise and  merged:**
![Screenshot 2024-10-21 160211](https://github.com/user-attachments/assets/47078f9e-f091-4e66-8427-4d112cb04107)

_**Note**_: Add level with gssoc-ext and hacktober-accepted labels! assign me to this PR !!

2024-10-22 10:03 UTC, smog-root commented
Add level2 cause i implemented 3 workflows! and updated a old workflow!  total 4 workflows!!

@ajay-dhangar

2024-10-23 03:43 UTC, ajay-dhangar requested changes
Can you recheck your code because it's content not related to us may be refreshing to the repo

2024-10-23 03:49 UTC, smog-root commented
What are the changes i should do in workflows??

2024-10-23 09:34 UTC, ajay-dhangar requested changes
We don't like to use other repos actions because our first priority is to use actions based on our content, codes, and our tech stack.

2024-10-23 09:34 UTC, ajay-dhangar commented on .github/workflows/pr_raise.yml
> +          "body": "Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our chaotic [CONTRIBUTING.md](https:/
checkout this content

2024-10-23 09:37 UTC, smog-root commented on .github/workflows/pr_raise.yml
> +          "body": "Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our chaotic [CONTRIBUTING.md](https:/
Hoo. Shit it was miss placed. I will change it!!

2024-10-23 09:39 UTC, smog-root commented
Changed!!

2024-10-27 14:55 UTC, ajay-dhangar approved these changes
Done

2024-10-27 14:55 UTC, merged