Vose Alia's Via Recursion
Ajay-Dhangar/algo pull request #1187
Opened 2024-10-22 16:24 UTC by MithanshuHedau

## 📥 Pull Request

issue :  #1186 

### Description
The Recursive Vose's Alias Method is an efficient algorithm designed for sampling from discrete probability distributions. It features a preprocessing time of O(n), allowing for quick setup, while enabling constant-time sampling at O(1), making it ideal for applications requiring rapid random sampling. The method effectively handles non-uniform distributions by categorizing probabilities into small and large lists, utilizing a recursive approach to build an alias table that accurately represents the distribution. Despite its recursive nature, the algorithm remains straightforward to implement and understand. Its versatility makes it applicable in various fields, including computer graphics, machine learning, and simulations, where fast and reliable sampling is essential. Overall, the Recursive Vose's Alias Method combines speed and flexibility, making it a valuable tool for efficient random sampling in discrete settings.

Fixes #1186 

### Type of change

- [✅ ] New feature (non-breaking change which adds functionality)
- [✅ ] Documentation update

### Checklist:

- [✅] My code follows the style guidelines of this project
- [✅ ] I have performed a self-review of my code
- [✅ ] I have commented my code, particularly in hard-to-understand areas
- [✅ ] I have added tests that prove my fix is effective or that my feature works
- [ ✅] New and existing unit tests pass locally with my changes
- [✅ ] Any dependent changes have been merged and published in downstream modules

2024-10-23 04:00 UTC, ajay-dhangar requested changes
update your `description` in few words like readable for SEO

2024-10-23 04:00 UTC, ajay-dhangar commented on docs/Recursion/VoseAlias.md
> +description: "The Recursive Vose's Alias Method is an efficient algorithm designed for sampling from discrete probability distributions. It features a preprocessing time of O(n), allowing for quick s
we are used `description` for our SEO in meta tag so, can you write in sort not in large word because we need to follow best practices.

2024-10-24 14:14 UTC, MithanshuHedau commented
@ajay-dhangar , can you please check now ,,, i have updated the Description as the SEO Point of view

2024-10-25 14:26 UTC, ajay-dhangar approved these changes
Done

2024-10-25 14:27 UTC, merged