LeetCode 75 Qs IssueNo.#453
Ajay-Dhangar/algo pull request #1188
Opened 2024-10-22 17:26 UTC by aditiverma-21

## 📥 Pull Request

### Description
I have All THE QUESTIONS OF ARRAY AND STRINGS in the present in practice of LEETCODE 75. Added more as discussed.

Fixes # 453

2024-10-25 16:32 UTC, aditiverma-21 commented
@ajay-dhangar please merge the PR

2024-10-26 16:52 UTC, aditiverma-21 commented
@ajay-dhangar HELLO,
Please merge this PR!!

2024-10-27 15:22 UTC, ajay-dhangar requested changes
Update your code based on suggestions

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/4. Can Place Flowers.md
> +
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/4. Can Place Flowers.md
> +description: Given an integer array flowerbed containing 0's and 1's, where 0 means empty and 1 means not empty, and an integer n, return true if n new flowers can be planted in the flowerbed without
add `"` for use description as  string

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/5. Reverse Vowels of a String.md
> +description: Given a string s, reverse only all the vowels in the string and return it.The vowels are 'a', 'e', 'i', 'o', and 'u', and they can appear in both lower and upper cases, more than once.
If you are using single quotes (`'`), then you need to write your string content in double quotes (`"`) with a close whole sentence. That way, the system can easily understand your code.

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/5. Reverse Vowels of a String.md
> +- s consist of printable ASCII characters.
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/9.String Compression.md
> +1 <= chars.length <= 2000
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/9.String Compression.md
> +description: If the group's length is 1, append the character to s. Otherwise, append the character followed by the group's length. The compressed string s should not be returned separately, but inst
fix mistakes and we need on sort of way like a few words for SEO.

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/8. Increasing Triplet Subsequence.md
> +- -231 <= nums[i] <= 231 - 1
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/8. Increasing Triplet Subsequence.md
> +
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/8. Increasing Triplet Subsequence.md
> +Given an integer array nums, return true if there exists a triple of indices (i, j, k) such that i < j < k and nums[i] < nums[j] < nums[k]. If no such indices exists, return false.
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/8. Increasing Triplet Subsequence.md
> +### Example 2
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/8. Increasing Triplet Subsequence.md
> +description: Given an integer array nums, return true if there exists a triple of indices (i, j, k) such that i < j < k and nums[i] < nums[j] < nums[k]. If no such indices exists, return false.
Not a good way 👎

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/7. Product of Array Except Self.md
> +- The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/7. Product of Array Except Self.md
> +---
this is part of the props for our setup so, you need to use `key - value` pair and value as a string only and not use any programming keywords

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/6. Reverse Words in a String.md
> +- 1 <= s.length <= 104
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-27 15:22 UTC, ajay-dhangar commented on docs/75 LeetCode Questions/Arrays&Strings/6. Reverse Words in a String.md
> +---
write description only in a single line

2024-10-28 12:58 UTC, aditiverma-21 commented on docs/75 LeetCode Questions/Arrays&Strings/4. Can Place Flowers.md
> +
Yes sure

2024-10-28 13:14 UTC, aditiverma-21 commented
@ajay-dhangar resolved the problems Please check

2024-10-29 03:36 UTC, ajay-dhangar requested changes
Checkout all files and change the code `<` and `>` because they are introducing as tags.

2024-10-30 14:11 UTC, closed without merging