Added  Abstraction in Object Oriented Programming
ajay-dhangar/algo pull request #1248
Opened 2024-10-24 14:30 UTC by tanishqkolhatkar93

## 📥 Pull Request

### Description
Abstraction in Java is the process of hiding unnecessary implementation details from the user, focusing on exposing only the essential functionalities. It allows developers to interact with objects at a higher level, without needing to understand the complexities of the underlying code. This ensures that the program is more modular, maintainable, and user-friendly.

Fixes #1195

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-10-24 14:36 UTC, tanishqkolhatkar93 commented
@ajay-dhangar please review and merge this PR

2024-10-25 14:36 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-25 14:36 UTC, ajay-dhangar commented on docs/Object Oriented Programming/Abstraction.md
> +# Abstraction
please follow our formate and carefully read our contributions guidelines for better understanding our structures

2024-10-26 15:09 UTC, tanishqkolhatkar93 commented
@ajay-dhangar I have made the requested changes please review it

2024-10-27 15:33 UTC, ajay-dhangar requested changes
Please update your code to follow the rules in our documentation. This includes using good practices, syntax, and formatting.

2024-10-27 15:33 UTC, ajay-dhangar commented on docs/Object Oriented Programming/Abstraction.md
> +
write within `---` and you can checkout format in our Contributions guideline

2024-10-27 15:33 UTC, ajay-dhangar commented on docs/Object Oriented Programming/Abstraction.md
> +### Multiple Interfaces <a name="multiple-interface"></a>
why write `<a name="multiple-interface"></a>`

2024-10-27 15:33 UTC, ajay-dhangar commented on docs/Object Oriented Programming/Abstraction.md
> +
😕 ... ⁉️

2024-10-27 15:33 UTC, ajay-dhangar commented on docs/Object Oriented Programming/Abstraction.md
> +```
❌

2024-10-27 15:33 UTC, ajay-dhangar commented on docs/Object Oriented Programming/Abstraction.md
> +
⁉️

2024-10-29 11:39 UTC, tanishqkolhatkar93 commented
@ajay-dhangar I have made the changes please review it

2024-10-31 15:24 UTC, ajay-dhangar approved these changes
Done

2024-10-31 15:34 UTC, ajay-dhangar approved these changes
👍

2024-10-31 15:42 UTC, merged