Added Multistage-graph.md
Ajay-Dhangar/algo pull request #1288
Opened 2024-10-25 15:33 UTC by shuvojitss

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-25 16:07 UTC, shuvojitss commented
This program is w.r.t issue #1279 which you assigned me.

2024-10-25 16:24 UTC, ajay-dhangar requested changes
Please read our [contribution guideline](https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md ) for a better understanding of our format and expectations. When writing content, please follow the guidelines to ensure that your contributions are accepted.

2024-10-25 16:24 UTC, ajay-dhangar commented on docs/dynamic-programming/Multistage-graph.md
> +id: MULTISTAGE GRAPH
Replace `id: MULTISTAGE GRAPH` with `id: multistage-graph`

2024-10-25 16:34 UTC, shuvojitss commented
@ajay-dhangar I have changed the id value as per required. If any other changes is required I will also do that. Please review it

2024-10-26 14:43 UTC, ajay-dhangar approved these changes
Done

2024-10-26 14:43 UTC, merged