Added Tarjan's Algorithm.
Ajay-Dhangar/algo pull request #1318
Opened 2024-10-26 09:36 UTC by AbhijitMotekar99

## 📥 Pull Request

### Description
Added Tarjan's Algoritm

Fixes #523 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-27 02:52 UTC, ajay-dhangar requested changes
Update your code based on suggestions

2024-10-27 02:52 UTC, ajay-dhangar commented on docs/Tarjan's Algorithm/Tarjan's.md
> +id: Tarjan's
replace `id: Tarjan's`1 with `id: tarjan`

2024-10-27 02:52 UTC, ajay-dhangar commented on docs/Tarjan's Algorithm/Tarjan's.md
> +title: Introduction to Tarjan's Algorithm
replace `title: Introduction to Tarjan's Algorithm` with `title: "Introduction to Tarjan's Algorithm"`

2024-10-27 02:52 UTC, ajay-dhangar commented on docs/Tarjan's Algorithm/Tarjan's.md
> +sidebar_label: Tarjan's Algorithm
replace `sidebar_label: Tarjan's Algorithm` with `sidebar_label: "Tarjan's Algorithm"`

2024-10-27 05:32 UTC, AbhijitMotekar99 commented
Hey @ajay-dhangar 
I done all changes.

2024-10-28 04:01 UTC, ajay-dhangar approved these changes
Done

2024-10-28 04:01 UTC, merged