Added Java content
Ajay-Dhangar/algo pull request #1321
Opened 2024-10-26 13:31 UTC by purnima2904

## 📥 Pull Request

### Description
Added detailed content on java including introduction, variables, operators and multithreading with code examples.

Fixes #625 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-27 08:05 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-27 08:05 UTC, ajay-dhangar commented on docs/languages/java/ex1.md
> +```java
you can try 

````md
```java title="Main.java"
public class Main {
  public static void main(String[] args) {
    System.out.println("Hello World");
  }
}
```
````

2024-10-27 08:05 UTC, ajay-dhangar commented on docs/languages/java/ex1.md
> +- The curly braces {} marks the beginning and the end of a block of code.
replace `{}` with ``` `{}` ```

2024-10-28 09:32 UTC, purnima2904 commented
@ajay-dhangar kindly review the changes made as per your request

2024-10-29 03:52 UTC, ajay-dhangar approved these changes
Done

2024-10-29 03:54 UTC, merged