chore: 🤖 Constant Product AMM Implementation
Ajay-Dhangar/algo pull request #1336
Opened 2024-10-26 18:52 UTC by yashksaini-coder

✅ Closes: #1290

## 📥 Pull Request

### Description
This PR raises a fix for the above mentioned issue to add the algorithm and approach for the Constant Product Automated market algorithm, with C code.

✅ Fixes #1290 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-10-26 18:53 UTC, yashksaini-coder commented
@ajay-dhangar review this PR and assign it to me with proper labels

2024-10-27 04:02 UTC, yashksaini-coder commented
@ajay-dhangar what's the status of my PR

2024-10-27 15:50 UTC, ajay-dhangar requested changes
Update your code based on our suggestion

2024-10-27 15:50 UTC, ajay-dhangar commented on .vscode/settings.json
don't push `.vscode/settings.json`

2024-10-27 15:50 UTC, ajay-dhangar commented on docs/Constant Product AMM/AMM.c
we need only `.md` files not `docs/Constant Product AMM/AMM.c`

2024-10-27 15:50 UTC, ajay-dhangar commented on docs/Constant Product AMM/Cost Product AMM.md
> +# 🤖 Simple Constant Product AMM Implementation
You need to follow our format and please carefully read our contribution guideline

2024-10-28 03:58 UTC, ajay-dhangar approved these changes
Done

2024-10-28 03:58 UTC, merged

2024-10-28 10:35 UTC, yashksaini-coder commented
@ajay-dhangar can you add hacktoberfest labels too