✅ [Idea]: KMP Algorithm for Pattern Searching
Ajay-Dhangar/algo pull request #1360
Opened 2024-10-27 09:31 UTC by yashksaini-coder

## 📥 Pull Request

### Description

This pull request adds comprehensive documentation for the KMP (Knuth-Morris-Pratt) pattern searching algorithm. The changes include creating a new category for the KMP algorithm and adding a detailed README file that explains the algorithm, its implementation, and usage examples.

Documentation additions:

* Created a new category for the KMP searching pattern with a description of the algorithm.
*  Added a detailed README file that includes an overview of the KMP algorithm, key features, how it works, implementation in Python, example usage, step-by-step example, performance comparison, common pitfalls, additional resources, and best practices.

✅ Fixes #1343 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-10-27 09:32 UTC, yashksaini-coder commented
@ajay-dhangar can you review this PR, and assign it  to me with proper labels

2024-10-27 18:18 UTC, yashksaini-coder commented
@ajay-dhangar can you review this PR and add proper labels to it.

2024-10-28 10:37 UTC, yashksaini-coder commented
@ajay-dhangar can you add `hacktoberfest` labels too

2024-10-28 14:44 UTC, yashksaini-coder commented
@ajay-dhangar I closed the PR to resolve the merge conflicts, cleared the conflicts, you can review it now.

2024-10-28 15:44 UTC, ajay-dhangar requested changes
update your code based on our format and syntax

2024-10-28 15:44 UTC, ajay-dhangar commented on docs/KMP searching pattern/readme.md
> +
write code based on our format

2024-10-30 04:14 UTC, ajay-dhangar requested changes
Please follow the `.jsx` and `.mdx` syntax for this pull request. Our project uses markdown plus React, so this syntax is required.

2024-10-30 04:14 UTC, ajay-dhangar commented on docs/KMP searching pattern/readme.md
> +    <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221125004358/image-660x398.png" alt="KMP Algorithm" width="500">
<img> is a non-void element. It requires a closing tag. Replace `<img>` with `<img />` to make it self-closing.

2024-10-30 05:39 UTC, yashksaini-coder commented
@ajay-dhangar can you review this PR, and add hacktoberfest labels too

2024-10-30 09:36 UTC, yashksaini-coder commented
@ajay-dhangar I have updated the code based on your specific requirements

2024-10-30 14:54 UTC, ajay-dhangar requested changes
Please recheck the code in your `docs/KMP searching pattern/readme.md` file. The content is not good, and does not meet our guidelines. Please revise the content to be more meaningful.

2024-10-30 14:56 UTC, yashksaini-coder commented
> Please recheck the code in your `docs/KMP searching pattern/readme.md` file. The content is not good, and does not meet our guidelines. Please revise the content to be more meaningful.

I'm sorry for that, as it happens I had many PRs in your repo so am having problems in handling all, No worries I will update it later tomorrow.

Also Happy Diwali 🎆 @ajay-dhangar

2024-10-31 05:08 UTC, yashksaini-coder commented
@ajay-dhangar I have added implementation in different languages with step-by-step explanation, Hope this changes are good

2024-10-31 15:41 UTC, ajay-dhangar approved these changes
Done

2024-10-31 15:41 UTC, merged