Create HierarchialClustering.md
Ajay-Dhangar/algo pull request #1367
Opened 2024-10-27 11:31 UTC by ananyag309

## 📥 Pull Request

### Description
Added hierarchial clustering algorithm
Fixes #1335 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-28 15:02 UTC, ajay-dhangar requested changes
update your code based on our suggestion

2024-10-28 15:02 UTC, ajay-dhangar commented on docs/machine-learning/HierarchialClustering.md
> +# Hierarchical Clustering Algorithm
please follow our format and syntax and also, carefully read our contribution guideline

2024-10-30 05:59 UTC, ananyag309 commented
@ajay-dhangar please review and merge it

2024-10-30 14:21 UTC, ajay-dhangar approved these changes
Done

2024-10-30 14:27 UTC, merged