Create SDG.md
Ajay-Dhangar/algo pull request #1380
Opened 2024-10-27 13:44 UTC by ananyag309

## 📥 Pull Request

### Description
added SGD

Fixes #1368 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-28 05:25 UTC, ananyag309 commented
@ajay-dhangar please merge it

2024-10-29 16:57 UTC, ajay-dhangar requested changes
You need write code based on our format

2024-10-29 16:57 UTC, ajay-dhangar commented on docs/machine-learning/SDG.md
> +Stochastic Gradient Descent (SGD) is an optimization algorithm used to minimize the loss function in machine learning and deep learning models. Unlike standard gradient descent, which calculates the
Please carefully read our contribution guidelines and follow our format

2024-10-29 17:28 UTC, ananyag309 commented
@ajay-dhangar please review it once and let me know if any further changes required

2024-10-30 14:19 UTC, ajay-dhangar requested changes
Please update the code based on the suggestions I've provided. Also, for mathematical formulas and equations, you should use `$...$` for a single line and `$$...$$` for a block.

2024-10-30 14:19 UTC, ajay-dhangar commented on docs/machine-learning/SDG.md
> +   where:
use `$` for math equation

2024-10-30 14:19 UTC, ajay-dhangar commented on docs/machine-learning/SDG.md
> +title: Stochastic Gradient Descent (SGD)
replace `title: Stochastic Gradient Descent (SGD)` with `title: "Stochastic Gradient Descent (SGD)"`

2024-10-30 16:05 UTC, ananyag309 commented
@ajay-dhangar is it fine now

2024-10-31 15:43 UTC, ajay-dhangar approved these changes
Okay

2024-10-31 15:43 UTC, merged