Hbos
Ajay-Dhangar/algo pull request #1527
Opened 2024-10-28 05:45 UTC by ananyag309

## 📥 Pull Request

### Description
Added the document

Fixes #1521 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-29 12:19 UTC, ananyag309 commented
@ajay-dhangar 
may i know what the issue is so that i can correct it?

2024-10-29 16:58 UTC, ajay-dhangar requested changes
follow our format

2024-10-29 16:58 UTC, ajay-dhangar commented on docs/machine-learning/HBOS.md
> +
⁉️

2024-10-29 17:25 UTC, ananyag309 commented
@ajay-dhangar please check now ... any further changes need please let me know

2024-11-01 03:14 UTC, ajay-dhangar approved these changes
Done

2024-11-01 03:18 UTC, merged