Add Documentation for Cloning a Linked List with Random and Next Pointers
Ajay-Dhangar/algo pull request #1529
Opened 2024-10-28 07:10 UTC by riyaa060

## 📥 Pull Request

### Description
This pull request introduces detailed documentation for cloning a linked list that includes both random and next pointers. The new documentation aims to clarify the process and provide a comprehensive guide for developers.

Fixes #1528 

### Type of change
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-28 15:15 UTC, ajay-dhangar requested changes
Write your code based on our format

2024-10-28 15:15 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/flattening-a-linked-list.md
> +
⁉️

2024-10-28 18:26 UTC, riyaa060 commented
Okay I will make changes then update

2024-11-01 03:17 UTC, ajay-dhangar approved these changes
Done

2024-11-01 03:17 UTC, merged