Yash/fix 1544
Ajay-Dhangar/algo pull request #1549
Opened 2024-10-28 14:23 UTC by yashksaini-coder

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-28 14:33 UTC, yashksaini-coder commented
@ajay-dhangar can you review my PR

2024-10-28 15:42 UTC, ajay-dhangar requested changes
can you carefully read our contribution guidelines and follow our formats

2024-10-28 15:42 UTC, ajay-dhangar commented on docs/Task Scheduling/Task-schedule.md
> +## Table of Contents
⁉️

2024-10-28 16:28 UTC, yashksaini-coder commented on docs/Task Scheduling/Task-schedule.md
> +## Table of Contents
I have added the correct format

2024-10-30 04:16 UTC, ajay-dhangar approved these changes
Done

2024-10-30 04:16 UTC, merged