Create a-very-useful-data-structure-linked-lists.md
Ajay-Dhangar/algo pull request #1572
Opened 2024-10-28 16:36 UTC by jainaryan04

fixes #1571

2024-10-29 13:53 UTC, jainaryan04 commented
@ajay-dhangar please merge

2024-11-01 05:08 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-01 05:08 UTC, ajay-dhangar commented on blog/a-very-useful-data-structure-linked-lists.md
> +}
close your code example with ```` ``` ````

2024-11-01 05:08 UTC, ajay-dhangar commented on blog/a-very-useful-data-structure-linked-lists.md
> +authors: [Aryan-Jain]
write your `Aryan-Jain` name and basic info in the `blog/authors.yml` file like https://github.com/ajay-dhangar/algo/blob/7814b98e8e0993e3b52f573f23810bb19afd453c/blog/authors.yml#L32

2024-11-05 08:02 UTC, jainaryan04 commented
done @ajay-dhangar

2024-11-05 10:15 UTC, ajay-dhangar approved these changes
Done

2024-11-05 10:15 UTC, merged