[Feature]: Adding Stargazers  animated gif
Ajay-Dhangar/algo pull request #1592
Opened 2024-10-29 06:37 UTC by yashksaini-coder

## 📥 Pull Request

### Description
Add a new component `AnimatedGIF.tsx` to render & display `gif` & `mp4` files easily.
Also exported the stargazers animation video.

Fixes #1557 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

---

@ajay-dhangar can you review this PR, and add proper labels to it. Also assign this issue to me.

2024-10-29 19:06 UTC, yashksaini-coder commented
Here is the final result:- 

[algo-1557.webm](https://github.com/user-attachments/assets/2a25fef6-d897-4efd-b757-a6f696017ae4)

2024-10-30 04:24 UTC, ajay-dhangar requested changes
Our repo is `https://github.com/ajay-dhangar/algo/`. So, can you modify based on our contents and resources

2024-10-30 04:24 UTC, ajay-dhangar commented on src/components/Homepage/HeroSection.tsx
>              Explore Algorithms <FaArrowRight className="ml-2" />
Replace `a` with `Link` and `href` with `to`

2024-10-30 05:07 UTC, yashksaini-coder commented
@ajay-dhangar I have done the requested changes to the `HeroSection.tsx`

2024-10-31 07:51 UTC, ajay-dhangar approved these changes
Done

2024-10-31 07:51 UTC, merged