Polynomial Multiplication Using Linked Lists
Ajay-Dhangar/algo pull request #1601
Opened 2024-10-29 13:24 UTC by nishthaa-m

## 📥 Pull Request

### Description
This pull request introduces a new feature that implements **Polynomial Multiplication using a linked list data structure**. The implementation allows users to define polynomials by specifying terms with coefficients and exponents, and then multiply two polynomials together, returning the resulting polynomial. This feature enhances the functionality of polynomial operations in the project.

The motivation behind this change is to provide a flexible and efficient way to handle polynomial calculations, making it easier for users to work with mathematical expressions programmatically.

Fixes #1546

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

**Test Cases:**

![image](https://github.com/user-attachments/assets/2d0017fe-5348-46b7-8bfd-eed24f9f072e)
![image](https://github.com/user-attachments/assets/68b49e19-e51b-4113-8950-c703a3b031c6)

2024-11-01 09:58 UTC, ajay-dhangar requested changes
we need only .md file so, can you write your code in markdown file for our docs

2024-11-05 08:45 UTC, nishthaa-m commented
@ajay-dhangar Made the necessary changes.
Kindly review them.

2024-11-05 10:18 UTC, ajay-dhangar requested changes
We need only `.md` files and they must be in the `docs` folder. Please remove any other files, such as `.cpp` files.

2024-11-05 11:31 UTC, nishthaa-m commented
@ajay-dhangar Updated it

2024-11-06 13:16 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-06 13:16 UTC, ajay-dhangar commented on docs/linked-list/Polynomial_multiplication.md
> +}
close your code example with ```` ``` ````

2024-11-09 09:34 UTC, ajay-dhangar approved these changes
Done

2024-11-09 09:40 UTC, merged