Create isPowerOfTwo.md
ajay-dhangar/algo pull request #1610
Opened 2024-10-29 15:29 UTC by kjl98

## 📥 Pull Request

### Description
To solve this problem, we can use bit manipulation, which is very efficient. The key observation here is that a number which is a power of two has exactly one bit set to 1 in its binary representation.

Fixes #1609 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-11-01 09:44 UTC, ajay-dhangar requested changes
update your id in good format for our `url`

2024-11-01 09:44 UTC, ajay-dhangar commented on java/isPowerOfTwo.md
> +id: isPowerOfTwo
replace `id: isPowerOfTwo` with `id: is-power-of-two`

2024-11-02 03:34 UTC, ajay-dhangar approved these changes
Done

2024-11-02 03:34 UTC, merged

2024-11-02 08:33 UTC, kjl98 commented
> Done

Thank you @ajay-dhangar for merging my changes.