added algo
Ajay-Dhangar/algo pull request #1635
Opened 2024-10-30 04:27 UTC by T-Fathima

## 📥 Pull Request

### Description
This pull request includes a solution to the character replacement problem using a sliding window approach. The main objective is to find the longest substring that can be made of the same character by replacing up to k characters in the input string. This approach maximizes the substring length while efficiently handling character replacements.

Fixes #1540 

### Type of change
- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

@ajay-dhangar Please review and merge my code under gssoc-ext and hacktoberfest.

2024-11-01 11:07 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-01 11:07 UTC, ajay-dhangar commented on docs/Sliding-Window/character-replacement.md
> +}
close your example code with ```` ``` ````

2024-11-01 11:20 UTC, T-Fathima reviewed
Done sir.

2024-11-02 03:31 UTC, ajay-dhangar approved these changes
Done

2024-11-02 03:31 UTC, merged