Added Fenwick Tree (Binary Indexed Tree) Algorithm.
Ajay-Dhangar/algo pull request #1645
Opened 2024-10-30 07:18 UTC by AbhijitMotekar99

## 📥 Pull Request

### Description
Added Fenwick Tree (Binary Indexed Tree) Algorithm.

Fixes #524 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-31 07:01 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-31 07:01 UTC, ajay-dhangar commented on docs/Fenwick Tree /FenwickTree.md
> +id: FenwickTree
replace `id: FenwickTree` with `id: fenwick-tree`

2024-10-31 07:01 UTC, ajay-dhangar commented on docs/Fenwick Tree /FenwickTree.md
> +![Graph Diagram](./Binary_index.png "Example of Graph for Fenwick tree")
image not found: Solve issue

2024-11-01 12:43 UTC, AbhijitMotekar99 commented
Hey @ajay-dhangar 
All changes done !

2024-11-01 15:07 UTC, ajay-dhangar requested changes
Please follow our contributions guide and also markdown (`.md` /`.mdx`) syntax

2024-11-01 15:07 UTC, ajay-dhangar commented on docs/Fenwick Tree /FenwickTree.md
> +![Fenwick Tree Diagram](https://media.geeksforgeeks.org/wp-content/cdn-uploads/BITSum.png "Example of Fenwick Tree for an Array")
Not a good format for images.

2024-11-01 15:07 UTC, ajay-dhangar commented on docs/Fenwick Tree /FenwickTree.md
> +![Graph Diagram](./Binary_index.png "Example of Graph for Fenwick tree")
also, check this

2024-11-04 06:03 UTC, AbhijitMotekar99 commented
Hey @ajay-dhangar 
Now check I resolved all conflicts and remove unnecessary lines.

2024-11-04 07:09 UTC, ajay-dhangar approved these changes
Done

2024-11-04 07:11 UTC, merged