Add page replacement algorithms
Ajay-Dhangar/algo pull request #1654
Opened 2024-10-30 09:20 UTC by Ananya-vastare

## 📥 Pull Request

### Description
Least Recently Used (LRU) and First-In, First-Out (FIFO) page replacement algorithms by enhancing the system's memory management capabilities. With LRU prioritizing pages based on recent usage and FIFO removing the oldest page first, this change provides users with a comparative analysis of these widely-used algorithms to optimize page replacement performance. This feature aims to improve system efficiency when handling memory references, making it a valuable addition to the project. No additional dependencies are required for this implementation.

Fixes # (issue number)
#1554 
### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-10-30 10:21 UTC, Ananya-vastare commented
@ajay-dhangar please let me know if I need to make any changes

2024-10-31 12:43 UTC, Ananya-vastare commented
@ajay-dhangar any updates please

2024-11-02 03:30 UTC, ajay-dhangar requested changes
First you need save your file with `.md` extension and follow our format

2024-11-02 03:30 UTC, ajay-dhangar commented on docs/Operating System/pagereplacementaglorithms.ms
> +Page replacement algorithms are essential in operating systems for managing memory efficiently when there is limited space. FIFO (First-In, First-Out) and LRU (Least Recently Used) are two fundamenta
not a good format

2024-11-02 03:31 UTC, Ananya-vastare commented
Okay will do that by the end of the day @ajay-dhangar

2024-11-03 10:49 UTC, Ananya-vastare commented
@ajay-dhangar please know if I need to make any changes

2024-11-03 14:30 UTC, Ananya-vastare commented
@ajay-dhangar please let me know if I need to make any changes

2024-11-04 03:54 UTC, ajay-dhangar requested changes
Update your code based on suggestions

2024-11-04 03:54 UTC, ajay-dhangar commented on Operating System/pagereplacementalgorithm.md
> +# Page Replacement Algorithm: Least Recently Used (LRU)
Please follow the syntax and format for our docs. If you have any questions, please don't hesitate to ask.

2024-11-05 11:41 UTC, closed without merging