Contains_duplicate file DSA problem added
Ajay-Dhangar/algo pull request #1676
Opened 2024-10-30 16:20 UTC by PradeepFSTdhane123

Contains_duplicate file DSA problem added

## 📥 Pull Request

### Description
Contains_duplicate file DSA problem added  with full explanation and approach.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-02 10:20 UTC, ajay-dhangar requested changes
Update code based on suggestions

2024-11-02 10:20 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Contains_duplicate.md
> +Initialization: We declare an unordered_set<int> uniques to store the unique numbers encountered during the iteration.
replace `unordered_set<int>` with ``` `unordered_set<int>` ```

2024-11-02 10:20 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Contains_duplicate.md
> +id: Contains-Duplicate-leetcode-217
We use the `id` value as a unique `url`.  So, we need write it in small letters.

2024-11-04 03:23 UTC, PradeepFSTdhane123 commented
@ajay-dhangar  changes successfully added please check pr #1802

2024-11-04 03:55 UTC, closed without merging