Add two files in Fundamentals
Ajay-Dhangar/algo pull request #1679
Opened 2024-10-30 17:50 UTC by AnushkaChouhan25

## 📥 Pull Request

### Description
Add Loops and Conditional Statements to the Fundamental Section

Fixes - Introduce a new subsection in the Fundamental #1537

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-31 06:55 UTC, ajay-dhangar requested changes
Update your code based on suggestions

2024-10-31 06:55 UTC, ajay-dhangar commented on docs/fundamentals/Conditional Statement.md
> +id: Coditional Statement
replace `id: Coditional Statement` with `id: coditional-statement`

2024-10-31 09:10 UTC, AnushkaChouhan25 commented
@ajay-dhangar Done

2024-11-02 03:50 UTC, ajay-dhangar approved these changes
Done

2024-11-02 03:50 UTC, merged