Added a problem on Merge K Sorted Arrays
Ajay-Dhangar/algo pull request #1718
Opened 2024-11-01 10:39 UTC by Riddhi12349

## 📥 Pull Request

### Description
Merge K Sorted Arrays so that final array is sorted in ascending order.

Fixes #1715 

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-02 11:02 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-02 11:02 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Merge_K_Sorted_Arrays.md
> +id: Merge K Sorted Arrays
replace `id: Merge K Sorted Arrays` with `id: merge-k-sorted-arrays`

2024-11-02 16:02 UTC, Riddhi12349 commented
done

2024-11-03 07:17 UTC, ajay-dhangar requested changes
Update your code based on suggestions

2024-11-03 07:17 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Merge_K_Sorted_Arrays.md
> +- A 2D array of integers `arr` of size k\*k.
replace `k\*k` with `$k\*k$`

2024-11-03 07:17 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Merge_K_Sorted_Arrays.md
> +- **Time Complexity**: O(K^2\* log(K)), where insertion and deletion in a Min Heap requires log K time and for all K^2 elements it takes (K^2 \* log(K)) time
replace `O(K^2\* log(K))` with `$O(K^2\* log(K))$`, `k^2` with `$k^2$`, and `(K^2 \* log(K))` with `$(K^2 \* log(K))$`

2024-11-03 07:17 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Merge_K_Sorted_Arrays.md
> +- **Space Complexity**: O(K) for the result array.
replace `O(K)` with `$O(K)$`

2024-11-03 15:06 UTC, Riddhi12349 commented
done

2024-11-04 03:57 UTC, ajay-dhangar approved these changes
Done

2024-11-04 04:02 UTC, merged