added regression algorithm
Ajay-Dhangar/algo pull request #1752
Opened 2024-11-02 16:18 UTC by KGupta2601

## 📥 Pull Request

### Description
added regression algorithm

Fixes #1583 

### Type of change

- [ ] New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-11-02 16:19 UTC, KGupta2601 commented
@ajay-dhangar kindly review my PR and provide the labels of gssoc extended and level 1

2024-11-03 07:42 UTC, ajay-dhangar approved these changes
Done

2024-11-03 07:42 UTC, ajay-dhangar commented on docs/machine-learning/regression_algorithm.md
> +title: Regression Algorithm (Supervised learning)
replace `title: Regression Algorithm (Supervised learning)` with `title: "Regression Algorithm (Supervised learning)"`

2024-11-03 07:43 UTC, ajay-dhangar requested changes
follow best practices  for our docs

2024-11-03 18:13 UTC, KGupta2601 commented
@ajay-dhangar kindly check now...I have made the changes

2024-11-04 04:01 UTC, ajay-dhangar approved these changes
Done

2024-11-04 04:01 UTC, merged