added documentation for recursion-depth
Ajay-Dhangar/algo pull request #1754
Opened 2024-11-02 16:35 UTC by Richajaishwal0

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-11-03 09:10 UTC, ajay-dhangar requested changes
Please follow our format and syntax when adding documentation. Refer to our docs format guidelines and our contributions guidelines.

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/advanced-topics.md
> +| recursion-depth-advanced | Advanced Recursion Depth Topics| Advanced Topics   | 8                | Advanced concepts related to recursion depth, including dynamic programming and backtracking. | ad
please follow our docs format and style

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/basic-concepts.md
> +| recursion-depth-basic-concepts | Basic Concepts of Recursion Depth | Basic Concepts    | 2                | Introduction to recursion and understanding recursion depth. | recursion, depth, basics
change format

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/binary-search-depth.md
> +| binary-search-recursion-depth| Binary Search Recursion Depth | Binary Search Example   | 5                | An example of recursion depth with binary search.   | binary-search, recursion, depth |
❌

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/binary-search-depth.md
> +  \]
use `$$ ... $$`

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/binary-search-depth.md
> +  \]
use `$$ ... $$` for math equation

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/factorial-depth.md
> +
❌

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/factorial-depth.md
> +- **Base Case**: The function returns `1` when \( n \) is 0 or 1, which stops the recursion.
replace `\(n \)` with `$n$`

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/factorial-depth.md
> +- **Memory Consumption**: Each recursive call adds to the stack, so for large \( n \), the program may run into stack overflow issues.
Please apply for the math equation `$` for inline and `$$` for block line. These are similar to \( or \) and \[ or \].

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/factorial-depth.md
> +\]
use `$$ ... $$`

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/fibonacci-depth.md
> +
❌

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/fibonacci-depth.md
> +
use `$`

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/fibonacci-depth.md
> +- **Optimization**: Memoization can greatly improve performance by storing previously computed values.
use `$`

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/examples/fibonacci-depth.md
> +
use `$$`

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/handling-depth-errors.md
> +
❌

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/handling-depth-errors.md
> +
close your code example with ```` ``` ````

2024-11-03 09:10 UTC, ajay-dhangar commented on docs/Recursion-depths/performance-consideration.md
> +| recursion-depth-performance| Recursion Depth and Performance  | Performance Considerations | 6                | Understanding how recursion depth affects algorithm performance. | performance, recur
❌

2024-11-03 09:59 UTC, ajay-dhangar commented on docs/Recursion-depths/Recursion.md
> +
this is not a good way so, please follow our format

2024-11-04 05:59 UTC, Richajaishwal0 commented
@ajay-dhangar I have updated the documentation (#1702). Please check and let me know if anything needs to be modified.

2024-11-04 07:16 UTC, ajay-dhangar approved these changes
Done

2024-11-04 07:26 UTC, merged