Create Depth_first_traversal.md
Ajay-Dhangar/algo pull request #1765
Opened 2024-11-03 06:22 UTC by shivenyadavs

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
**Description**
This change introduces the Depth-First Traversal (DFT) algorithm as an addition to the project, providing implementations for preorder, inorder, and postorder traversals in a binary tree structure. This feature enhances the project's tree traversal capabilities, allowing users to explore nodes by going as deep as possible along each branch before backtracking.

**Summary of Changes:**
**Added Depth-First Traversal (DFT) functionality**: Includes recursive implementations for preorder, inorder, and postorder traversal methods.
**C++ Code Implementations:** Provides C++ examples to illustrate each traversal type.

**Motivation and Context**
Depth-First Traversal is a fundamental algorithm used widely in tree-based data structures and search processes. Adding this functionality aligns with project goals of covering essential data structures and algorithms, expanding the use cases for tree traversals in real-world scenarios such as expression evaluation and hierarchical data processing.

Fixes #1761 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-11-03 10:27 UTC, shivenyadavs commented
@ajay-dhangar please check the changes

2024-11-03 14:13 UTC, shivenyadavs commented
@ajay-dhangar please merge this pr

2024-11-03 15:37 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-03 15:37 UTC, ajay-dhangar commented on docs/Depth_first_traversal.md
> +}
close your code example with ```` ``` ````

2024-11-03 15:37 UTC, ajay-dhangar commented on docs/Depth_first_traversal.md
> +title: Depth-First Traversal (DFT)
replace `title: Depth-First Traversal (DFT)` with `title: "Depth-First Traversal (DFT)"`

2024-11-03 16:17 UTC, shivenyadavs commented
please check the changes

2024-11-04 04:08 UTC, ajay-dhangar approved these changes
Done

2024-11-04 04:11 UTC, merged