Rotate List to practice skills section
Ajay-Dhangar/algo pull request #1803
Opened 2024-11-04 05:33 UTC by shriyadindi

## 📥 Pull Request

### Description
Rotate List to practice skills section

Fixes #1770

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-04 09:26 UTC, ajay-dhangar requested changes
First, you need to pull and sync our latest commit. Once you have done that, you can then write your code.

2024-11-04 11:12 UTC, shriyadindi commented
@ajay-dhangar Okay, I'll give the update by eod.

2024-11-04 13:16 UTC, shriyadindi commented
@ajay-dhangar I tried reforking and cloning the repository as there is problem with syncing and updation, and I'm not able to clone the website it is showing like this.
![Screenshot 2024-11-04 184551](https://github.com/user-attachments/assets/639ac108-1d39-47a5-99bf-ef412ab9371f)

2024-11-05 04:12 UTC, ajay-dhangar commented
> @ajay-dhangar I tried reforking and cloning the repository as there is problem with syncing and updation, and I'm not able to clone the website it is showing like this. ![Screenshot 2024-11-04 184551](https://private-user-images.githubusercontent.com/126611334/382767000-639ac108-1d39-47a5-99bf-ef412ab9371f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Nzk1MDAsIm5iZiI6MTczMDc3OTIwMCwicGF0aCI6Ii8xMjY2MTEzMzQvMzgyNzY3MDAwLTYzOWFjMTA4LTFkMzktNDdhNS05OWJmLWVmNDEyYWI5MzcxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwNDAwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTZjMGEyYzI5MTk1MmNjYzVhNjIyYzViOTA0OWZiZjFhZWQ0ZmVkODFiYzZmZmUwYTdkNmI4NjFkMjc1OWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bd4ZpTge11kD130l2sbGFOtYRw7f2N28_qXep6LRt90)

I'm sorry, but you must delete the algo project from your machine or system and reclone our repo with the latest commit. If you get errors, please read this Stack Overflow question: [[Error: "1824 bytes of body are still expected" while cloning repository from GitHub](https://stackoverflow.com/questions/78396934/error-1824-bytes-of-body-are-still-expected-while-cloning-repository-from-git)]

2024-11-05 04:19 UTC, shriyadindi commented
@ajay-dhangar I tried to make the changes in a new pull request, can you please review it.
https://github.com/ajay-dhangar/algo/pull/1834

2024-11-05 10:21 UTC, closed without merging