Added euclidean_Algorithm for NumberTheory
Ajay-Dhangar/algo pull request #1810
Opened 2024-11-04 09:31 UTC by Richajaishwal0

## 📥 Pull Request

### Description
This file provides a comprehensive and beginner-friendly guide to the Extended Euclidean Algorithm, explaining its definition, workings, and applications in number theory and competitive programming. It includes step-by-step explanations, code implementations in Python, C++, and Java, and practical examples to illustrate how to compute the greatest common divisor (GCD) and the coefficients that satisfy Bézout's identity. The document is structured with clear headings and mathematical expressions to enhance understanding, making it an essential resource for those interested in learning about this important algorithm.

Fixes #1795

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-11-05 04:33 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +---
add `id` for url

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +\]
replace 

```md
\[
...
\]
```

with

```md
$$
...
$$
```

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +The Extended Euclidean Algorithm is a method used to find the **Greatest Common Divisor (GCD)** of two integers, \(a\) and \(b\). But it does more than just that—it also finds two coefficients, \(x\)
replace `\( ... \)` with `$ ... $`

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +This equation is known as **Bézout's identity**. The values of \(x\) and \(y\) can be very useful in solving equations where you need whole number solutions, such as linear Diophantine equations.
use `$` for inline maths formulas and syntax

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +
use `$$ ... $$` for block line maths formulas and syntax

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +
use `$`

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +
use `$` and `$$` for maths formulas and syntax

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +
use `$`

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +
use `$`

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +
use `$`

2024-11-05 04:33 UTC, ajay-dhangar commented on docs/Number theory/Euclidean_ALgorithm.md
> +
use `$$`

2024-11-07 07:54 UTC, Richajaishwal0 commented
@ajay-dhangar pls check and say if  any further changes are needed.

2024-11-09 03:03 UTC, ajay-dhangar approved these changes
done

2024-11-09 03:04 UTC, merged