Added Circular array documentation
Ajay-Dhangar/algo pull request #1841
Opened 2024-11-05 10:22 UTC by Richajaishwal0

## 📥 Pull Request

### Description
The circular array, or circular buffer, is a linear data structure that wraps around to the beginning once it reaches the end, allowing efficient use of memory by reusing space without reallocating the array. It operates with a fixed size and is commonly utilized in queue implementations and buffering systems. Key operations include initialization, insertion (enqueue), deletion (dequeue), and checking the full or empty status. The provided implementations in Python, Java, and C++ demonstrate how to manage the circular nature of the array while maintaining optimal performance for these operations. The time complexity for enqueueing and dequeueing is \(O(1)\), while the space complexity is \(O(n)\), where \(n\) is the fixed size of the array.

Fixes #1817

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-11-06 13:35 UTC, ajay-dhangar requested changes
update only `id` in `docs/Circular_array/Introduction.md` file

2024-11-06 13:35 UTC, ajay-dhangar commented on docs/Circular_array/Introduction.md
> +id: Circular Array introduction
replace `id: Circular Array introduction` with `id: circular-array-introduction`

2024-11-06 15:46 UTC, Richajaishwal0 commented
@ajay-dhangar please check once

2024-11-07 02:55 UTC, ajay-dhangar approved these changes
Done

2024-11-07 02:56 UTC, merged