handling json data in sql
Ajay-Dhangar/algo pull request #1864
Opened 2024-11-05 18:04 UTC by jainaryan04

### Description
Handling JSON data within SQL combines the flexibility of JSON with the robustness of SQL databases. By leveraging native JSON support, developers can efficiently store, query, and manipulate JSON data, optimizing database operations for modern applications.

Fixes #1863 

### Type of change
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-11-06 14:02 UTC, ajay-dhangar requested changes
update your `id` based on suggestions

2024-11-06 14:02 UTC, ajay-dhangar commented on docs/languages/SQL/sql-25.md
> +id: SQL-JSON-Data
replace `id: SQL-JSON-Data` with `id: sql-json-data`

2024-11-06 17:03 UTC, jainaryan04 commented
done @ajay-dhangar

2024-11-07 02:57 UTC, ajay-dhangar approved these changes
Done

2024-11-07 03:02 UTC, merged