Next smaller Element Using Stack
Ajay-Dhangar/algo pull request #1869
Opened 2024-11-06 08:17 UTC by riyaa060

## 📥 Pull Request

### Description
This pull request adds detailed documentation explaining the algorithm to find the next smaller element for each element in an array using a stack.
Fixes #1746 

### Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-06 13:57 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-06 13:57 UTC, ajay-dhangar commented on docs/Stack/Next_Smaller_Element_Using_Stack
save your file with `.md` extension

2024-11-06 13:57 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Add two numbers represented as linked lists.md
> +     \]
not a good way you need try math formula like `$$ ... $$`

2024-11-06 13:57 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Add two numbers represented as linked lists.md
> +sidebar_label:  Adding Two Numbers Represented as Linked Lists
You need to delete the write space because we need only one, not two.

2024-11-07 07:45 UTC, riyaa060 commented
I have saved file with extension md

2024-11-09 03:18 UTC, closed without merging