#122 Added 5 New Algorithms under String Algorithms
Ajay-Dhangar/algo pull request #187
Opened 2024-10-07 15:58 UTC by pratheekv39

## 📥 Pull Request

### Description

1. Summary of Change: Implemented 5 algorithms under the String Algorithms section: 
   - Apostolico–Giancarlo Algorithm
   - BNDM (Backward Nondeterministic Dawg Matching) Algorithm
   - Bitap Algorithm (Approximate String Matching)
   - Commentz-Walter Algorithm
   - Shift-Or Algorithm

2. Issue Fixed: Resolved issue #122  by adding the necessary algorithms to the string algorithms section.

3. Motivation: The changes enhance the algorithm coverage and provide detailed implementations for each string matching algorithm.

4. Context: Detailed comments were added where necessary to improve clarity and code understanding.

5. Dependencies:  No new dependencies introduced.

Fixes #122 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X ] New and existing unit tests pass locally with my changes
- [X ] Any dependent changes have been merged and published in downstream modules

@ajay-dhangar  Please add the required labels GSSOC Ext and Hacktoberfest . Thanks....

2024-10-08 05:51 UTC, pratheekv39 commented
@ajay-dhangar Can you please review it and add GSSOC Ext and Hacktoberfest labels to it . Thanks......

2024-10-08 08:03 UTC, ajay-dhangar requested changes
Hi @pratheekv39,

Thank you for your contributions! I have a few suggestions to improve the consistency and readability of our project:

1. **File Naming Best Practices**: Please rename the following files to follow a consistent, clear naming convention:
   - `ApostolicoGiancarlo.md` → `apostolico-giancarlo.md`
   - `BNDM.md` → `bndm.md`
   - `Bitap.md` → `bitap.md`
   - `CommentzWalter.md` → `commentz-walter.md`
   - `ShiftOr.md` → `shift-or.md`

   Using lowercase letters and hyphens between words makes file names more uniform and easier to manage across different platforms.

2. **LaTeX Syntax in Markdown Files**: When writing mathematical expressions in LaTeX, please ensure that you're using the correct syntax. For inline math, use single dollar signs (`$ ... $`), and for block math, use double dollar signs (`$$ ... $$`). This ensures proper rendering across all markdown viewers that support LaTeX.

Example for inline math: `$ O\left(\frac{n}{w}\right) $`

Example for block math:
```
$$
O\left(\frac{n}{w}\right)
$$
```

Let me know if you need any assistance with these changes.

Best regards,  
@ajay-dhangar

2024-10-08 08:03 UTC, ajay-dhangar commented on docs/algorithms/string-algorithms/ApostolicoGiancarlo.md
> +- **Average Case: O(n)**
replace `O(n)` with `$O(n)$`

2024-10-08 08:03 UTC, ajay-dhangar commented on docs/algorithms/string-algorithms/ApostolicoGiancarlo.md
> +- **Worst Case: O(n * m)**
replace `O(n * m)` with `$O(n \times m)$`

2024-10-08 08:03 UTC, ajay-dhangar commented on docs/algorithms/string-algorithms/ApostolicoGiancarlo.md
> +- **Space Complexity: O(m + n)**
replace `O(m + n)` with `$O(m + n)$`

2024-10-08 08:03 UTC, ajay-dhangar commented on docs/algorithms/string-algorithms/BNDM.md
> +- **Best Case: O(n / w)**
replace `O(n / w)` with `$O\left(\frac{n}{w}\right)$`

2024-10-08 08:03 UTC, ajay-dhangar commented on docs/algorithms/string-algorithms/BNDM.md
> +- **Average Case: O(n)**
replace `O(n)` with `$O(n)$`

2024-10-08 08:03 UTC, ajay-dhangar commented on docs/algorithms/string-algorithms/BNDM.md
> +- **Worst Case: O(n * m)**
replace `O(n * m)` with `$O(n \times m)$`

2024-10-08 08:03 UTC, ajay-dhangar commented on docs/algorithms/string-algorithms/BNDM.md
> +- **Space Complexity: O(m)**
replace `O(m)` with `$O(m)$`

2024-10-08 12:23 UTC, pratheekv39 commented
@ajay-dhangar I have made the changes that you requested . Please check once...

2024-10-08 13:42 UTC, ajay-dhangar approved these changes
Done

2024-10-08 16:37 UTC, ajay-dhangar commented
> @ajay-dhangar I have made the changes that you requested . Please check once...

@pratheekv39, you need to sync our latest code. I've resolved the error, so first, sync with `git pull origin main`, push the code to your branch, and then resolve any remaining errors.

2024-10-09 16:28 UTC, pratheekv39 commented
@ajay-dhangar Ok sir , I will sync the lastest code and send the updates by Monday . Been busy with some work lately:(

2024-10-14 15:14 UTC, pratheekv39 commented
@ajay-dhangar I have resolved and updated (synced) my branch and pushed the code. Can you now approve the PR???

2024-10-14 17:07 UTC, merged