Add Size_of_largest_BST_in_binary_tree.md
Ajay-Dhangar/algo pull request #1870
Opened 2024-11-06 08:24 UTC by Riddhi12349

## 📥 Pull Request

### Description
Size of largest BST in binary tree by recursively calling for left and right subtrees and return the maximum of two calls. 

Fixes #1851 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-06 13:48 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-06 13:48 UTC, ajay-dhangar commented on docs/DSA-Problem-Solution/Size_of_largest_BST_in_binary_tree.md
> +We will traverse the tree in a bottom-up manner. For every traversed node, we return the maximum and minimum values in the subtree rooted at that node. The idea is to determine whether the subtree ro
delete line `7` to `11`

2024-11-06 16:44 UTC, Riddhi12349 commented
done

2024-11-07 02:58 UTC, ajay-dhangar approved these changes
Done

2024-11-07 02:58 UTC, merged