Addition of Hashing | Issue #174
Ajay-Dhangar/algo pull request #188
Opened 2024-10-07 16:10 UTC by Shariq2003

## 📥 Pull Request

### Description
I have added hashing in-depth with most important problems and its solutions.
Fixes #174 
![image](https://github.com/user-attachments/assets/fd6c8681-ea1b-47b6-a92d-9ee2cbea5c91)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-10-08 08:07 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-08 08:07 UTC, ajay-dhangar commented on docs/Hashing/what-is-hashing.md
> +1. **Fast Data Retrieval**: Hashing allows for quick data retrieval, enabling average-case constant time complexity \(O(1)\) for search, insert, and delete operations.
replace `\(O(1)\) ` with `$O(1)$`

2024-10-08 08:09 UTC, Shariq2003 commented
Okay sir

2024-10-08 09:39 UTC, Shariq2003 commented on docs/Hashing/what-is-hashing.md
> +1. **Fast Data Retrieval**: Hashing allows for quick data retrieval, enabling average-case constant time complexity \(O(1)\) for search, insert, and delete operations.
> replace `\(O(1)\) ` with `$O(1)$`

@ajay-dhangar please check now

2024-10-08 09:39 UTC, Shariq2003 commented
@ajay-dhangar sir, please review now

2024-10-08 14:34 UTC, ajay-dhangar commented
> @ajay-dhangar sir, please review now

@Shariq2003,  you need to sync your code with the latest changes in the main branch. To do this, you can use git pull origin main. Once your code is up to date, the error should be resolved.

2024-10-08 14:54 UTC, Shariq2003 commented
> > @ajay-dhangar sir, please review now
> 
> @Shariq2003, you need to sync your code with the latest changes in the main branch. To do this, you can use `git pull origin main`. Once your code is up to date, the error should be resolved.

what errors @ajay-dhangar sir, could u please explain

2024-10-08 14:54 UTC, Shariq2003 commented
My always take a pull after updating my fork repo, before starts working on any issue.

2024-10-08 16:31 UTC, ajay-dhangar commented
> I always take a pull after updating my fork repo, before start working on any issue.

you need first sync our latest code after pull

2024-10-08 16:36 UTC, Shariq2003 commented
> > I always take a pull after updating my fork repo, before start working on any issue.
> 
> you need first sync our latest code after pull

yes sir I always do the same, could u please explain me any issue that happens

2024-10-08 16:51 UTC, Shariq2003 commented
@ajay-dhangar sir, could u please let me know why my PR is in pending state.

2024-10-09 05:31 UTC, ajay-dhangar requested changes
@Shariq2003, your code is working but you need to sync our latest code. I've resolved the error, so first, sync with `git pull origin main`, push the code to your branch, and then resolve any remaining errors.

2024-10-09 05:38 UTC, Shariq2003 commented
> @Shariq2003, your code is working but you need to sync our latest code. I've resolved the error, so first, sync with `git pull origin main`, push the code to your branch, and then resolve any remaining errors.

Okay sir

2024-10-09 12:03 UTC, Shariq2003 commented
> @Shariq2003, your code is working but you need to sync our latest code. I've resolved the error, so first, sync with `git pull origin main`, push the code to your branch, and then resolve any remaining errors.

please review now.

2024-10-09 14:30 UTC, ajay-dhangar approved these changes
Done

2024-10-09 14:36 UTC, merged