Added  the algorithm for Adjacency List
Ajay-Dhangar/algo pull request #1898
Opened 2024-11-06 16:42 UTC by shuvojitss

## 📥 Pull Request

### Description
Added the Adjacency List program under Graph.This program is w.r.t issue no. #1876 which is related to this program.

Fixes #1876

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-07 03:24 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-07 03:24 UTC, ajay-dhangar commented on docs/graphs/Adjacency-List.md
> +4-->3
write within ```` ``` ````

2024-11-07 03:42 UTC, shuvojitss commented on docs/graphs/Adjacency-List.md
> +4-->3
Done

2024-11-09 09:36 UTC, ajay-dhangar approved these changes
Done

2024-11-09 09:36 UTC, merged