This PR adds a feature to find the median of a stream of numbers using a two-heap approach.
Ajay-Dhangar/algo pull request #1904
Opened 2024-11-06 18:23 UTC by T-Fathima

## 📥 Pull Request

### Description
Implemented `MedianFinder` class with `addNum` and `findMedian` methods.
- Used max-heap and min-heap to maintain the balance for efficient median calculation.

Fixes #1886 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-07 03:21 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-07 03:21 UTC, ajay-dhangar commented on docs/heap/Add-Merge-k-sorted-lists.md
> +id: Heap-data-Structure-4
replace `id: Heap-data-Structure-4` with `id: heap-data-structure-4`

2024-11-07 03:21 UTC, ajay-dhangar commented on docs/heap/Median-of-a-stream.md
> +id: Heap-data-Structure-5
replace `id: Heap-data-Structure-5` with `id: heap-data-structure-5`

2024-11-07 04:11 UTC, T-Fathima commented
@ajay-dhangar Ok done. Now u can check.

2024-11-09 03:09 UTC, ajay-dhangar approved these changes
Done

2024-11-09 03:09 UTC, merged