blog on comparing sorting algorithms
Ajay-Dhangar/algo pull request #1941
Opened 2024-11-08 07:28 UTC by jainaryan04

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1940 

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-11-09 07:46 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Space Complexity**: \(O(1)\)
replace `\(O(n^2)\)` with `$O(n^2)$`, `\(O(n)\)` with `$O(n)$` , and `\(O(1)\)` with `$\(O(1)\)$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Space Complexity**: \(O(1)\)
use `$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Space Complexity**: \(O(1)\)
use `$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Space Complexity**: \(O(n)\)
use `$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Cons**: Worst-case time can be \(O(n^2)\); not stable
use `$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Space Complexity**: \(O(1)\)
use `$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Pros**: Fast for fixed-digit data; stable
use `$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +- **Space Complexity**: \(O(n + k)\)
use `$`

2024-11-09 07:46 UTC, ajay-dhangar commented on blog/comparing-sortings.md
> +| Counting Sort   | \(O(n + k)\)         | \(O(n + k)\)          | \(O(n + k)\)     | Yes    | Small integer range, limited data range |
use `$`

2024-11-09 10:01 UTC, jainaryan04 commented
done @ajay-dhangar

2024-11-09 10:22 UTC, ajay-dhangar approved these changes
Done

2024-11-09 10:27 UTC, ajay-dhangar commented
To add yourself as an author (`ARYAN-JAIN`), please add your information to the following file: https://github.com/ajay-dhangar/algo/blob/main/blog/authors.yml. Please use the following format: 

```yml
narendra-dhangar:
  name: Narendra Dhangar
  title: B.Tech (CSE) Student
  url: https://www.instagram.com/narendra_dh._05/
  image_url: https://github.com/narendra-dhangar.png
  email: narendradhangar63@gmail.com
  page: true # Turns the feature on
  description: >
    A dedicated Computer Science and Engineering student with a passion for problem-solving and algorithms. I am constantly exploring various fields of computer science, from data structures and algorithms to web development and machine learning. As an avid learner, I enjoy tackling challenging problems and sharing knowledge with the community. Eager to contribute to open-source projects and make an impact in the tech world.

  socials:
    linkedin: narendra-dhangar-880558297
    github: narendra-dhangar
```

2024-11-09 10:37 UTC, jainaryan04 commented
@ajay-dhangar I am already in the file

2024-11-10 12:48 UTC, jainaryan04 commented
@ajay-dhangar please merge

2024-11-10 14:02 UTC, ajay-dhangar approved these changes
Your mistake is that you use the author as "ARYAN-JAIN", but in the author file the correct name is "Aryan-Jain". So I fix this. And Done

2024-11-10 14:02 UTC, merged