Shell Sort #1909
Ajay-Dhangar/algo pull request #1947
Opened 2024-11-08 15:10 UTC by laxmikandivalasa

Shell Sort #1909

Idea Title
Add a new sorting algorithm

Idea Description
An optimized version of insertion sort. Shell Sort sorts elements far apart first, then progressively reduces the gap.

Potential Benefits
 Improves user experience
 Enhances learning
 Adds a new feature
 Improves code quality
 Other

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-08 17:21 UTC, laxmikandivalasa commented
@ajay-dhangar can you review this pr

2024-11-09 04:42 UTC, laxmikandivalasa commented
@ajay-dhangar can you have a look at these prs

2024-11-09 08:06 UTC, laxmikandivalasa commented
can you label this with level 2 since i included 2 issues

2024-11-09 08:15 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-09 08:15 UTC, ajay-dhangar commented on docs/greedy-algorithms/kruskals-algorithm.md
> +title: Kruskal's Algorithm
replace `title: Kruskal's Algorithm` with `title: "Kruskal's Algorithm"`

2024-11-09 08:15 UTC, ajay-dhangar commented on docs/greedy-algorithms/kruskals-algorithm.md
> +sidebar_label: Kruskal's Algorithm
replace `sidebar_label: Kruskal's Algorithm` with `sidebar_label: "Kruskal's Algorithm"`

2024-11-09 08:15 UTC, ajay-dhangar commented on docs/greedy-algorithms/kruskals-algorithm.md
> +
close your code example with ```` ``` ````

2024-11-09 08:15 UTC, ajay-dhangar commented on docs/greedy-algorithms/kruskals-algorithm.md
> +}
Write your code example within ```` ``` ````

for example

````md
```java
// your code here
```
````

2024-11-09 08:15 UTC, ajay-dhangar commented on docs/greedy-algorithms/prims-algorithm.md
> +sidebar_label: Prim's Algorithm
replace `Prim's Algorithm` with `"Prim's Algorithm"`

2024-11-09 08:15 UTC, ajay-dhangar commented on docs/greedy-algorithms/prims-algorithm.md
careful read our contribution guideline https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md#d-adding-code-blocks

2024-11-09 08:15 UTC, ajay-dhangar commented on docs/sortings/shell-sort .md
careful read our contribution guideline https://github.com/ajay-dhangar/algo/blob/main/CONTRIBUTING.md#d-adding-code-blocks

2024-11-09 08:24 UTC, laxmikandivalasa commented
updated both  the files!!
@ajay-dhangar I'd like to accept for any other changes

2024-11-09 09:35 UTC, laxmikandivalasa commented
can you review this pr again!!

2024-11-09 09:54 UTC, ajay-dhangar approved these changes
Done

2024-11-09 10:01 UTC, merged