[ feature ]: Added priority search doc. in searching-algorithm folder
Ajay-Dhangar/algo pull request #1955
Opened 2024-11-09 07:49 UTC by Jivanjamadar

## 📥 Pull Request

### Description:
Added Priority search algorithm doc. in searching-algorithm folder which is part of algorithms folder.

**Description of algo:**
Priority Search efficiently finds the closest rectangle to a query point in a 2D plane by sorting rectangles based on priority. It offers fast search times when the data is sorted but can degrade to linear time in the worst case. It's commonly used in GIS, graphics, and robotics for spatial queries.

Dependencies: NA
Fixes: #1951

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-09 09:25 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-11-09 09:25 UTC, ajay-dhangar commented on docs/algorithms/Searching Algorithms/PrioritySearch.md
> +id: Priority-search-algorithm
replace `id: Priority-search-algorithm` with `id: priority-search-algorithm`

2024-11-09 10:47 UTC, Jivanjamadar commented on docs/algorithms/Searching Algorithms/PrioritySearch.md
> +id: Priority-search-algorithm
changes has been made. review it.

2024-11-10 09:39 UTC, ajay-dhangar approved these changes
Done

2024-11-10 09:40 UTC, merged