Added Algo for Dutch flag Algorithm
Ajay-Dhangar/algo pull request #271
Opened 2024-10-08 11:05 UTC by shimmer12

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-08 11:05 UTC, shimmer12 commented
solved issue #260

2024-10-09 15:13 UTC, ajay-dhangar commented
> solved issue #260 @ajay-dhangar please merge this under suitable labels

@shimmer12, please sync your fork with the latest changes from the main repository. I've resolved the `backtracking-questions.md` error at line 56.

Here's what you need to do:
1. Fetch the latest updates from the main repository:
   ```
   git fetch upstream
   git merge upstream/main
   ```
2. Push the merged changes to your fork:
   ```
   git push origin your-branch
   ```
3. After syncing, resolve any remaining issues.

Please don't hesitate to let me know if you encounter any problems.

2024-10-09 15:17 UTC, ajay-dhangar requested changes
update code based on suggestions

2024-10-09 15:17 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/Dutch-flag-algo.md
> +The Dutch National Flag Algorithm efficiently sorts an array containing only 0's, 1's, and 2's in a single traversal of the array. It achieves optimal time complexity of O(N) and operates in-place, m
replace `O(N)` with `$O(N)$`

2024-10-09 15:17 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/Dutch-flag-algo.md
> +- **Space Complexity: O(1)**
replace `O(1)` with `$O(1)$`

2024-10-09 15:17 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/Dutch-flag-algo.md
> +- **Worst Case: O(N)**
replace `O(N)` with `$O(N)$`

2024-10-09 15:17 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/Dutch-flag-algo.md
> +- **Average Case: O(N)**
replace `O(N)` with `$O(N)$`

2024-10-09 15:17 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/Dutch-flag-algo.md
> +- **Best Case: O(N)**
replace `O(N)` with `$O(N)$`

2024-10-09 15:24 UTC, shimmer12 commented
I have made the required changes
thank you !

2024-10-10 04:10 UTC, ajay-dhangar approved these changes
Done

2024-10-10 04:10 UTC, merged