Added Josephus Queries problem
Ajay-Dhangar/algo pull request #272
Opened 2024-10-08 11:06 UTC by J-B-Mugundh

## 📥 Pull Request

### Description
Added Josephus Queries solution. Elaborated the solution of recursion in C++, Java, Python, Javascript, Go

Fixes #207 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-08 11:10 UTC, J-B-Mugundh commented
@ajay-dhangar I'm not sure why build is failing! Could you please check!

2024-10-09 08:31 UTC, ajay-dhangar commented
> @ajay-dhangar I'm not sure why build is failing! Could you please check!

@J-B-Mugundh, please sync your fork with the latest changes from the main repository. I've resolved the `backtracking-questions.md` error at line 56.

Here's what you need to do:
1. Fetch the latest updates from the main repository:
   ```
   git fetch upstream
   git merge upstream/main
   ```
2. Push the merged changes to your fork:
   ```
   git push origin your-branch
   ```
3. After syncing, resolve any remaining issues.

Please don't hesitate to let me know if you encounter any problems.

2024-10-09 08:59 UTC, J-B-Mugundh commented
@ajay-dhangar Updated bro!

2024-10-09 10:41 UTC, ajay-dhangar requested changes
update your code based on suggestions for good practices

2024-10-09 10:41 UTC, ajay-dhangar commented on docs/Recursion/Josephus-Queries.md
> +- \(1 \leq k \leq n \leq 1,000,000,000\)
replace 

```md
-  \(1 \leq q \leq 100,000\)
- \(1 \leq k \leq n \leq 1,000,000,000\)
```

with

```md
- $1 \leq q \leq 100,000$
- $1 \leq k \leq n \leq 1,000,000,000$
```

for best practice

2024-10-09 10:41 UTC, ajay-dhangar commented on docs/Recursion/Josephus-Queries.md
> +2. For more than one child, the \(k\)-th removal can be computed by reducing the problem size by 1 each time we remove a child.
replace `\(k\)-th` with `$k^{th}$`

2024-10-09 10:41 UTC, ajay-dhangar commented on docs/Recursion/Josephus-Queries.md
> +Let `josephus(n, k)` be the function that returns the position of the \(k\)-th child to be removed when there are \(n\) children.
replace `\(k\)-th` with `$k^{th}$` and `\(n\)` with `$n$`

2024-10-09 10:41 UTC, ajay-dhangar commented on docs/Recursion/Josephus-Queries.md
> +- If \(n = 1\), return \(1\) (the only child).
replace `\(n = 1\)` with `$n = 1$` and `\(1\)` with `$1$`

2024-10-09 10:41 UTC, ajay-dhangar commented on docs/Recursion/Josephus-Queries.md
> +  \]
replace 

```md
\[
  josephus(n, k) = (josephus(n-1, k) + k) \% n
 \]
```
with

```md
$$
josephus(n, k) =
\begin{cases} 
0 & \text{if } n = 1, \\
(josephus(n-1, k) + k) \% n & \text{if } n > 1.
\end{cases}
$$
```

2024-10-09 10:41 UTC, ajay-dhangar commented on docs/Recursion/Josephus-Queries.md
> +
replace `\(O(n)\)` with `$O(n)$` and `\(n\)` with `$n$`

2024-10-09 10:41 UTC, ajay-dhangar commented on docs/Recursion/Josephus-Queries.md
> +
also, update the LaTeX-style math formula

2024-10-09 12:04 UTC, J-B-Mugundh commented
@ajay-dhangar Updated bro! Thanks so for much for your time and efforts!

2024-10-09 15:19 UTC, ajay-dhangar approved these changes
Done

2024-10-09 15:19 UTC, merged