Create tries
Ajay-Dhangar/algo pull request #320
Opened 2024-10-08 21:49 UTC by nishant4500

## 📥 Pull Request

Important content for day-other as trie data structure has been added.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-09 16:03 UTC, ajay-dhangar requested changes
You need to write your file name as `tries.md`. You can then choose a topic with a structured format from our folders and files. The file structure is located at https://ajay-dhangar.github.io/algo/dsa-roadmap/.

2024-10-10 12:17 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-10 12:17 UTC, ajay-dhangar commented on docs/tries.md
> +```
Try Mermaid Graph for better understanding and good UI/UX. It follows best practices, and you can check out https://mermaid.js.org/ for reference.

2024-10-10 14:04 UTC, nishant4500 commented
@ajay-dhangar Hey sir could you please merged now i think now i made all the changes with new UI and if you con please mark it level 2

2024-10-10 16:15 UTC, ajay-dhangar approved these changes
Done

2024-10-10 16:16 UTC, merged