Create TreeSort.md
Ajay-Dhangar/algo pull request #327
Opened 2024-10-09 04:05 UTC by Gopal0Gupta

## 📥 Pull Request

### Description
Tree Sort has been implemented. It builds a Binary Search Tree (BST) from input elements and retrieves them in sorted order via an in-order traversal. This algorithm is efficient in balanced cases but can degrade to O(n²) when the tree becomes unbalanced.

Fixes #323 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-09 04:57 UTC, Gopal0Gupta commented
@ajay-dhangar please merge it

2024-10-09 16:04 UTC, ajay-dhangar requested changes
update code based on suggestions

2024-10-09 16:04 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/TreeSort.md
> + ) in the worst case, making it less suitable for practical use in many scenarios compared to other algorithms like QuickSort or MergeSort.
rearrange formats

2024-10-10 05:46 UTC, Gopal0Gupta commented on docs/algorithms/sorting-algorithms/TreeSort.md
> + ) in the worst case, making it less suitable for practical use in many scenarios compared to other algorithms like QuickSort or MergeSort.
is it okk now

2024-10-10 05:46 UTC, Gopal0Gupta commented
> update code based on suggestions

Done

2024-10-10 12:18 UTC, merged