Linked list problems
Ajay-Dhangar/algo pull request #347
Opened 2024-10-09 10:55 UTC by iking07

## 📥 Pull Request

### Description
I have added practice problems on Linked List data structure topic wise

Fixes # 183

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-09 10:57 UTC, iking07 commented
Please check only the last commit for addition of linked list problems.

2024-10-10 13:53 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-10 13:53 UTC, ajay-dhangar commented on docs/linked-list/Practice-Problems.md
> +  - [Sorted insert for circular linked list](geeksforgeeks.org/problems/sorted-insert-for-circular-linked-list/1)
replace `geeksforgeeks.org/problems/sorted-insert-for-circular-linked-list/1` with `https://geeksforgeeks.org/problems/sorted-insert-for-circular-linked-list/1`

2024-10-10 13:53 UTC, ajay-dhangar commented on docs/linked-list/Practice-Problems.md
> +id: Practice-Problems-on Linked-List
replace `id: Practice-Problems-on Linked-List` with `id: practice-problems-on-linked-list`

2024-10-10 16:13 UTC, ajay-dhangar approved these changes
Done

2024-10-10 16:13 UTC, merged