added stooge sort
Ajay-Dhangar/algo pull request #348
Opened 2024-10-09 11:08 UTC by ananyag309

Fixes #148 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-09 16:23 UTC, ajay-dhangar requested changes
update code based on suggestions

2024-10-09 16:23 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/StoogeSort.md
> +  - Despite its simplicity, Stooge sort is inefficient with a time complexity of **O(n^2.7095)**, making it one of the least efficient sorting algorithms.
replace `**O(n^2.7095)**` with `$O(n^{2.7095})$`

2024-10-09 16:23 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/StoogeSort.md
> +- **Best Case: O(n^2.7095)**
replace `O(n^2.7095)` with `$O(n^{2.7095})$`

2024-10-09 16:23 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/StoogeSort.md
> +- **Average Case: O(n^2.7095)**
reply `O(n^2.7095)` with `$O(n^{2.7095})$`

2024-10-09 16:23 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/StoogeSort.md
> +- **Worst Case: O(n^2.7095)**
reply `O(n^2.7095)` with `$O(n^{2.7095})$`

2024-10-09 16:23 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/StoogeSort.md
> +- **Space Complexity: O(n)**
reply `O(n)` with `$O(n)$`

2024-10-09 17:17 UTC, ananyag309 commented
@ajay-dhangar please check

2024-10-10 00:26 UTC, ajay-dhangar approved these changes
Done

2024-10-10 00:26 UTC, merged