look and say recursion algorithm integrated
Ajay-Dhangar/algo pull request #390
Opened 2024-10-09 18:58 UTC by 17arindam

## 📥 Pull Request

### Description
Integrated look and say algorithm which contain Introduction Problem Statement Approach Pseudo Code Algorithm
Implementation in C++

Fixes #311 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-09 18:58 UTC, 17arindam commented
@ajay-dhangar please review my pr

2024-10-10 01:06 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-10 01:06 UTC, ajay-dhangar commented on docs/Recursion/look-and-say.md
> +}
close your code example with ```` ``` ````

2024-10-10 10:58 UTC, 17arindam commented
@ajay-dhangar i have corrected it please review

2024-10-10 15:56 UTC, ajay-dhangar approved these changes
Done

2024-10-10 15:56 UTC, merged