Add SQL Tutorial Files
Ajay-Dhangar/algo pull request #410
Opened 2024-10-10 07:13 UTC by IkkiOcean

## 📥 Pull Request

### Description
Closes: #298 
This PR introduces a comprehensive set of SQL tutorial files designed to help users understand and utilize SQL for database management. The tutorials cover essential topics, including:

- Introduction to SQL
- What Can SQL do?
- RDBMS
- SQL Statements
- Basic SQL Commands (SELECT)
- Examples of queries 

### Type of change
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code- [x] I have added tests that prove my fix is effective or that my feature works

2024-10-10 11:08 UTC, ajay-dhangar requested changes
can you follow our Docs format and We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-11 00:57 UTC, IkkiOcean commented
> can you follow our Docs format and We need on top
> 
> ```
> ---
> id: ___
> title: ___
> sidebar_label: ___
> sidebar_position: ___
> description: ___
> tags: [___, __, ]
> ---
> ```
> 
> ### Detailed Guidelines
> * id: Unique identifier for the route.
> * title: Title of the problem.
> * sidebar_label: Problem number or label for the sidebar.
> * tags: Relevant tags for the problem.
> * description: A short SEO-friendly description. No HTML tags.

<img width="1275" alt="Screenshot 2024-10-11 at 6 25 34 AM" src="https://github.com/user-attachments/assets/ca0df813-eef8-47e6-a397-fc0ea482336a">



- done

2024-10-11 09:25 UTC, IkkiOcean commented
@ajay-dhangar requested changes has been delivered. kindly review!

2024-10-11 16:52 UTC, shivay-coding requested changes
Now, follow our structure and suggestions in all of your code and files. This will make our documentation content much better.

2024-10-11 16:52 UTC, shivay-coding commented on docs/languages/SQL/sql-1.md
> +id: "sql_tutorial_1"
Replace the `id: "sql_tutorial_1"` with `id: "introduction-to-sql"`. This will make the URL more readable and understandable, which will help with SEO.

2024-10-11 16:52 UTC, shivay-coding commented on docs/languages/SQL/sql-1.md
> +============
delete line 9 to 11

2024-10-11 16:52 UTC, shivay-coding commented on docs/languages/SQL/sql-1.md
> +===================
also, delete line 17 to 19

2024-10-11 16:52 UTC, shivay-coding commented on docs/languages/SQL/sql-1.md
> +
replace line 23 to 24 with `## What is SQL?``

2024-10-11 16:52 UTC, shivay-coding commented on docs/languages/SQL/sql-1.md
> +What Can SQL do?
replace 

```md
What Can SQL do?
----------------
```

with

```md
## What Can SQL do?
```

2024-10-11 18:13 UTC, IkkiOcean commented
@shivay-coding made all the changes you asked for in all the files. kindly review.

2024-10-13 07:19 UTC, IkkiOcean commented
@ajay-dhangar please look into it as I have comtthe requestes changes

2024-10-13 15:31 UTC, ajay-dhangar approved these changes
done

2024-10-13 15:32 UTC, merged