Added algorithm for Doubly Linked List in C
Ajay-Dhangar/algo pull request #438
Opened 2024-10-10 14:45 UTC by Mansi07sharma

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-10 16:09 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-10 16:09 UTC, ajay-dhangar commented on docs/linked-list/Doubly-linked-list-C.md
> +id: DoublyLinkedList
replace `id: DoublyLinkedList` with `id: doubly-linked-list`

2024-10-11 05:23 UTC, Mansi07sharma commented
@ajay-dhangar done changes.

2024-10-11 16:54 UTC, shivay-coding approved these changes
Thank you for your contributions to Algo. Your work is good, and I appreciate your efforts.

2024-10-11 16:58 UTC, merged