Added RedBlack BST and Sentinel Search
Ajay-Dhangar/algo pull request #442
Opened 2024-10-10 16:31 UTC by purnima2904

## 📥 Pull Request

### Description
In the Binary Search Tree i have added about Red Black Tree explaining in detail its application , advantages and disadvantages , code , rules and properties
In the Searching Algorithm i have added about Sentinel Search explaining in detail about its use case , code, complexity , definition and characteristics

Fixes #436 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-11 04:11 UTC, purnima2904 commented
Hello @ajay-dhangar kindly review this PR.

2024-10-12 08:45 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-12 08:45 UTC, ajay-dhangar commented on docs/binary-search-tree/RedBlackTree.md
> +- Leaf nodes are also counted as black nodes. So, a red-black tree of height h has black height >= h/2.
replace `>` with `&gt;`

2024-10-12 08:45 UTC, ajay-dhangar commented on docs/binary-search-tree/RedBlackTree.md
> +- Height of a red-black tree with n nodes is h<= 2 log2(n + 1).
replace `<` with `&lt;`

2024-10-12 08:45 UTC, ajay-dhangar commented on docs/binary-search-tree/RedBlackTree.md
> +2B  8B 15R 25B
replace 

```md
    10B
   /   \
  5R    20B
 / \    /  \
2B  8B 15R 25B
```

with

````md
```
    10B
   /   \
  5R    20B
 / \    /  \
2B  8B 15R 25B
```
````

**OR**

if possible then try to use the mermaid graph (https://mermaid.js.org/)

2024-10-13 08:23 UTC, closed without merging