Added BST search insert and delete
Ajay-Dhangar/algo pull request #452
Opened 2024-10-10 17:54 UTC by haseebzaki-07

## 📥 Pull Request

### Description
Added BST search insert and delete operations in the Binary Search Tree Section
Fixes #404 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-10-11 17:05 UTC, ajay-dhangar requested changes
update code based on suggestion

2024-10-11 17:05 UTC, ajay-dhangar commented on docs/binary-search-tree/delete-BST.md
> +}
close your code example with ```` ``` ````

2024-10-11 17:05 UTC, ajay-dhangar commented on docs/binary-search-tree/insert-BST.md
> +}
close your code example with ```` ``` ````

2024-10-11 17:05 UTC, ajay-dhangar commented on docs/binary-search-tree/search-BST.md
> +}
close your code example with ```` ``` ````

2024-10-11 17:46 UTC, haseebzaki-07 commented
hey @ajay-dhangar I fixed the ending of the codes.

2024-10-12 10:20 UTC, ajay-dhangar approved these changes
Done

2024-10-12 10:20 UTC, merged