Added a start algorithm
Ajay-Dhangar/algo pull request #457
Opened 2024-10-10 19:03 UTC by mehul-m-prajapati

## 📥 Pull Request

### Description
Added a start algorithm

Fixes #371 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-11 17:06 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-11 17:06 UTC, ajay-dhangar commented on docs/graphs/shortest-path-algorithms/A-star-algorithm.md
> +
close your code example with ```` ``` ````

2024-10-11 17:14 UTC, mehul-m-prajapati commented on docs/graphs/shortest-path-algorithms/A-star-algorithm.md
> +
@ajay-dhangar : okay done.

2024-10-12 10:21 UTC, ajay-dhangar approved these changes
Done

2024-10-12 10:25 UTC, merged