Added Determine if Two Strings Are Close Leetcode Solution
Ajay-Dhangar/algo pull request #474
Opened 2024-10-11 03:35 UTC by shravya312

## 📥 Pull Request

### Description
Added Determine if Two Strings Are Close Leetcode Solution

Fixes #287 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-11 03:38 UTC, shravya312 commented
Hii @ajay-dhangar Can u review the pr

2024-10-11 09:39 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-11 09:39 UTC, ajay-dhangar commented on docs/leetcode-Solutions/determine-if-two-strings-are-close.md
> +Time Complexity: O(n) <br>
replace `<br>` with `<br />` because our project is based on `.mdx` + `.jsx` / `.tsx`

2024-10-11 09:40 UTC, shravya312 commented
> update your code based on suggestions

Okay sure

2024-10-11 09:44 UTC, shravya312 commented
I have updated the code according to suggestion @ajay-dhangar 
![image](https://github.com/user-attachments/assets/bf525df9-8ecd-428a-9c62-0aae397d523f)

2024-10-11 16:52 UTC, shravya312 commented
Hii @ajay-dhangar I have done the changes suggested can u review it

2024-10-12 10:26 UTC, ajay-dhangar approved these changes
Done

2024-10-12 10:26 UTC, merged