Strandsort
Ajay-Dhangar/algo pull request #492
Opened 2024-10-11 08:07 UTC by priyashuu

## 📥 Pull Request

### Description
shell sort was already there  , so i add strand sort 
Strand Sort is a recursive, comparison-based sorting algorithm that works by pulling out sorted sublists (strands) from the original list and then merging them together to create the final sorted list. Strand Sort works best with linked lists due to its insertions and extraction steps but can also be implemented with arrays.

Fixes #303 

### Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

![image](https://github.com/user-attachments/assets/7454efc0-b3ba-41a1-8175-7b71f31fdb14)

2024-10-12 01:56 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-12 01:56 UTC, ajay-dhangar commented on docs/algorithms/sorting-algorithms/OddEvenSort.md
> +
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-12 04:33 UTC, priyashuu commented
![image](https://github.com/user-attachments/assets/4aa1ebfb-a56b-4d85-ba0c-31827044454e)

2024-10-12 10:49 UTC, priyashuu commented
done

2024-10-12 10:50 UTC, priyashuu commented
@ajay-dhangar done

2024-10-12 18:37 UTC, priyashuu commented
@ajay-dhangar done with the changes

2024-10-13 12:54 UTC, priyashuu commented
@ajay-dhangar done with the changes

2024-10-13 15:29 UTC, ajay-dhangar commented
> @ajay-dhangar done with the changes

Please commit and push your updated code to this PR. Once you have completed your changes, please let me know so I can review and merge your changes.

2024-10-14 05:39 UTC, priyashuu commented
@ajay-dhangar  done sir

2024-10-14 17:14 UTC, ajay-dhangar approved these changes
...

2024-10-14 17:14 UTC, merged