Added String Algorithm issue #499
Ajay-Dhangar/algo pull request #560
Opened 2024-10-12 05:41 UTC by kRajoria121

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #499 

### Type of change

- [ ] New feature (non-breaking change which adds functionality)

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-12 16:15 UTC, kRajoria121 commented
can you increase the level ? if you can?

2024-10-13 09:30 UTC, ajay-dhangar requested changes
update code based on suggestions

2024-10-13 09:30 UTC, ajay-dhangar commented on docs/String algorithm/Rabin-karp-Algorithm.md
> +```
delete line `230` because not need in  end  ```` ``` ````

2024-10-13 09:30 UTC, ajay-dhangar commented on docs/String algorithm/Z-Algorithm.md
> +```
delete code ```` ``` ```` from line number 168

2024-10-13 09:30 UTC, ajay-dhangar commented on docs/String algorithm/kmp-algorithm.md
> +```
delete code ```` ``` ```` from line number 259

2024-10-13 12:47 UTC, kRajoria121 commented
Done

2024-10-13 15:19 UTC, ajay-dhangar approved these changes
🆗

2024-10-13 15:19 UTC, merged

2024-10-13 15:46 UTC, kRajoria121 commented
can you increase the level ? any how I'm just asking..