Create Searching-Algorithm.md
Ajay-Dhangar/algo pull request #581
Opened 2024-10-12 12:57 UTC by Bhumika-00

## 📥 Pull Request

### Description
Updated searching algo

Fixes # (575)

### Type of change

- [no ] Bug fix (non-breaking change which fixes an issue)
- [ yes] New feature (non-breaking change which adds functionality)
- [no ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ yes] Documentation update

### Checklist:

- [yes ] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my code
- [yes ] I have commented my code, particularly in hard-to-understand areas
- [yes ] I have added tests that prove my fix is effective or that my feature works
- [no ] New and existing unit tests pass locally with my changes
- [no ] Any dependent changes have been merged and published in downstream modules

2024-10-12 13:00 UTC, Bhumika-00 commented
I have done this please review it

2024-10-13 15:18 UTC, Bhumika-00 commented
It's completed

On Sun, 13 Oct, 2024, 8:47 pm Ajay Dhangar, ***@***.***>
wrote:

> Assigned #581 <https://github.com/ajay-dhangar/algo/pull/581> to
> @Bhumika-00 <https://github.com/Bhumika-00>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ajay-dhangar/algo/pull/581#event-14619902207>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKOHTVQE3WRK3VPHB2C3DV3Z3KFHNAVCNFSM6AAAAABP2MS246VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGYYTSOJQGIZDANY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-10-14 16:52 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-14 16:52 UTC, ajay-dhangar commented on arrays/Searching-Algorithm.md
> +
write your code example like

````md
```
// your code here
```
````

for example 

````md
```
 procedure binarySearch(A : sorted list of items, target)
    left = 0
    right = length(A) - 1
    while left <= right do
        mid = (left + right) / 2
        if A[mid] == target then
            return mid
        else if A[mid] < target then
            left = mid + 1
        else
            right = mid - 1
    end while
    return -1
end procedure
```
````

2024-10-14 16:52 UTC, ajay-dhangar commented on arrays/Searching-Algorithm.md
> +
write your code example like

````md
```
// your code here
```
````

for example 

````md
```
 procedure binarySearch(A : sorted list of items, target)
    left = 0
    right = length(A) - 1
    while left <= right do
        mid = (left + right) / 2
        if A[mid] == target then
            return mid
        else if A[mid] < target then
            left = mid + 1
        else
            right = mid - 1
    end while
    return -1
end procedure
```
````

2024-10-14 16:52 UTC, ajay-dhangar commented on arrays/Searching-Algorithm.md
> +- Time Complexity: O(log n)
replace `O(log n)` with `$O(log n)$`

2024-10-14 16:52 UTC, ajay-dhangar commented on arrays/Searching-Algorithm.md
> +- Space Complexity: O(1)
and also `O(1)` with `$O(1)$`

2024-10-14 16:52 UTC, ajay-dhangar commented on arrays/Searching-Algorithm.md
> +
write your code example within 

````md
```jsx
// your code here
```
````

2024-10-14 17:23 UTC, Bhumika-00 commented
Changes have been made into pr #718

On Mon, 14 Oct, 2024, 10:23 pm Ajay Dhangar, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> update your code based on suggestions
> ------------------------------
>
> In arrays/Searching-Algorithm.md
> <https://github.com/ajay-dhangar/algo/pull/581#discussion_r1799822001>:
>
> > + procedure binarySearch(A : sorted list of items, target)
> +    left = 0
> +    right = length(A) - 1
> +    while left <= right do
> +        mid = (left + right) / 2
> +        if A[mid] == target then
> +            return mid
> +        else if A[mid] < target then
> +            left = mid + 1
> +        else
> +            right = mid - 1
> +    end while
> +    return -1
> +end procedure
> +
>
> write your code example like
>
> ```// your code here```
>
> for example
>
> ``` procedure binarySearch(A : sorted list of items, target)    left = 0    right = length(A) - 1    while left <= right do        mid = (left + right) / 2        if A[mid] == target then            return mid        else if A[mid] < target then            left = mid + 1        else            right = mid - 1    end while    return -1end procedure```
>
> ------------------------------
>
> In arrays/Searching-Algorithm.md
> <https://github.com/ajay-dhangar/algo/pull/581#discussion_r1799822534>:
>
> > + procedure binarySearch(A : sorted list of items, target)
> +    left = 0
> +    right = length(A) - 1
> +    while left <= right do
> +        mid = (left + right) / 2
> +        if A[mid] == target then
> +            return mid
> +        else if A[mid] < target then
> +            left = mid + 1
> +        else
> +            right = mid - 1
> +    end while
> +    return -1
> +end procedure
> +
>
> write your code example like
>
> ```// your code here```
>
> for example
>
> ``` procedure binarySearch(A : sorted list of items, target)    left = 0    right = length(A) - 1    while left <= right do        mid = (left + right) / 2        if A[mid] == target then            return mid        else if A[mid] < target then            left = mid + 1        else            right = mid - 1    end while    return -1end procedure```
>
> ------------------------------
>
> In arrays/Searching-Algorithm.md
> <https://github.com/ajay-dhangar/algo/pull/581#discussion_r1799822788>:
>
> > +    left = 0
> +    right = length(A) - 1
> +    while left <= right do
> +        mid = (left + right) / 2
> +        if A[mid] == target then
> +            return mid
> +        else if A[mid] < target then
> +            left = mid + 1
> +        else
> +            right = mid - 1
> +    end while
> +    return -1
> +end procedure
> +
> +##Complexity
> +- Time Complexity: O(log n)
>
> replace O(log n) with $O(log n)$
> ------------------------------
>
> In arrays/Searching-Algorithm.md
> <https://github.com/ajay-dhangar/algo/pull/581#discussion_r1799823289>:
>
> > +    right = length(A) - 1
> +    while left <= right do
> +        mid = (left + right) / 2
> +        if A[mid] == target then
> +            return mid
> +        else if A[mid] < target then
> +            left = mid + 1
> +        else
> +            right = mid - 1
> +    end while
> +    return -1
> +end procedure
> +
> +##Complexity
> +- Time Complexity: O(log n)
> +- Space Complexity: O(1)
>
> and also O(1) with $O(1)$
> ------------------------------
>
> In arrays/Searching-Algorithm.md
> <https://github.com/ajay-dhangar/algo/pull/581#discussion_r1799826383>:
>
> > +  let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
> +
> +  let jumpIndex = jumpSearch(arr, 7);
> +  let exponentialIndex = exponentialSearch(arr, 7);
> +  let interpolationIndex = interpolationSearch(arr, 7);
> +
> +  return (
> +    <div>
> +      <h3>Advanced Searching Algorithms</h3>
> +      <p><b>Jump Search Index:</b> {jumpIndex}</p>
> +      <p><b>Exponential Search Index:</b> {exponentialIndex}</p>
> +      <p><b>Interpolation Search Index:</b> {interpolationIndex}</p>
> +    </div>
> +  )
> +}
> +
>
> write your code example within
>
> ```jsx// your code here```
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ajay-dhangar/algo/pull/581#pullrequestreview-2367173054>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKOHTVV43BKIGNEVQ2KXJGDZ3PZHXAVCNFSM6AAAAABP2MS246VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRXGE3TGMBVGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-15 01:35 UTC, closed without merging

2024-10-15 02:14 UTC, Bhumika-00 commented
Please review pr #718

On Tue, 15 Oct, 2024, 7:05 am Ajay Dhangar, ***@***.***>
wrote:

> Closed #581 <https://github.com/ajay-dhangar/algo/pull/581>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ajay-dhangar/algo/pull/581#event-14649195797>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BKOHTVQXZQWUCDN4N5TMOJ3Z3RWPLAVCNFSM6AAAAABP2MS246VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGY2DSMJZGU3TSNY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>