Divide and Conquer Algorithm
Ajay-Dhangar/algo pull request #598
Opened 2024-10-12 17:03 UTC by pragna7

Description
New Algorithm-Divide and Conquer Algorithm

Assigned #384 issue

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-14 17:20 UTC, ajay-dhangar approved these changes
ok

2024-10-14 17:36 UTC, pragna7 commented
could you please review it and merge it

2024-10-15 11:07 UTC, pragna7 commented
Can I know the issue occurred , what changes i have to make?

2024-10-16 15:52 UTC, ajay-dhangar requested changes
update your code based on suggestions and also, applied in all file and read more about [Math Equations](https://docusaurus.io/docs/markdown-features/math-equations)

2024-10-16 15:52 UTC, ajay-dhangar commented on docs/algorithms/Divide and Conquer Algorithm/Strassen'sAlgorithm.md
> +---
first you need rename your file `Strassen'sAlgorithm.md` to `strassen-algorithm.md` for best practices

2024-10-16 15:52 UTC, ajay-dhangar commented on docs/algorithms/Divide and Conquer Algorithm/Strassen'sAlgorithm.md
> +
replace your some code like

1. `O(n^{\log_2 7}) ≈ O(n^{2.81})` to `$O(n^{\log_2 7}) ≈ O(n^{2.81})$`
2. `\(n \times n\)` to `$n \times n$`
3. `\(O(n^3)\)` with `$O(n^3)$`
4. `\(O(n^{2.81})\)` with `$O(n^{2.81})$`

2024-10-16 15:52 UTC, ajay-dhangar commented on docs/algorithms/Divide and Conquer Algorithm/Strassen'sAlgorithm.md
> +   - If the input size is \(1 \times 1\), it multiplies the single elements.
replace `\(1 \times 1\)` with `$1 \times 1$`

2024-10-16 15:52 UTC, ajay-dhangar commented on docs/algorithms/Divide and Conquer Algorithm/Strassen'sAlgorithm.md
> +   - The `main` function initializes two \(2 \times 2\) matrices and calls the `strassen` function to multiply them.
replace `\(2 \times 2\)` with `$2 \times 2$`

2024-10-16 15:52 UTC, ajay-dhangar commented on docs/algorithms/Divide and Conquer Algorithm/Strassen'sAlgorithm.md
> +Strassen's Algorithm significantly reduces the complexity of matrix multiplication by using a divide-and-conquer approach, achieving a time complexity of approximately \(O(n^{2.81})\). Although it is
replace `\(O(n^{2.81})\)` with `$O(n^{2.81})$`

2024-10-19 17:37 UTC, pragna7 commented
i committed changes can you merge it now

2024-10-19 17:38 UTC, pragna7 commented on docs/algorithms/Divide and Conquer Algorithm/Strassen'sAlgorithm.md
> +Strassen's Algorithm significantly reduces the complexity of matrix multiplication by using a divide-and-conquer approach, achieving a time complexity of approximately \(O(n^{2.81})\). Although it is
i committed changes

2024-10-21 00:20 UTC, closed without merging