added Boyer-Moore-algorithm for Strings
Ajay-Dhangar/algo pull request #607
Opened 2024-10-12 19:44 UTC by Hamza1821

## 📥 Pull Request
added Boyer-Moore-algorithm for Strings
### 
### **please assign this to me under gssoc-ext**

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-13 08:11 UTC, Hamza1821 commented
sir please merge this

2024-10-14 15:08 UTC, Hamza1821 commented
please merge it sir

2024-10-15 10:56 UTC, ajay-dhangar commented
> [Hamza1821](/Hamza1821)

Can you share with me the issue number or a link to the issue that you are referring to?

2024-10-15 12:04 UTC, Hamza1821 commented
Sir i didnot created the issue for it

2024-10-15 17:02 UTC, ajay-dhangar requested changes
`package.json` and `package-lock.json` are automatically generated, so don't edit them.

2024-10-15 17:02 UTC, ajay-dhangar commented on package.json
> +    "algo": "file:",
Why did you add line 26? I think it should be deleted.

2024-10-15 18:01 UTC, Hamza1821 commented on package.json
> +    "algo": "file:",
I have not added it

2024-10-16 15:54 UTC, ajay-dhangar commented on package.json
> +    "algo": "file:",
you need delete line number 26 and repush

2024-10-16 16:36 UTC, Hamza1821 commented
Done now please merge

2024-10-17 05:38 UTC, ajay-dhangar commented
I see also, lock file

![{265D6052-D8D9-4197-90B3-C89F2EA350E9}](https://github.com/user-attachments/assets/c842cd12-dbd3-47c0-83f3-6565d2aae525)

Can you please check out your changes and fix this? The file is too large for me to see the changes directly.

2024-10-17 06:20 UTC, closed without merging