Solved Bug : There is nothing inside Programming Fundamentals section, adding fundamentals.
Ajay-Dhangar/algo pull request #608
Opened 2024-10-12 20:06 UTC by AbhijitMotekar99

## 📥 Pull Request

### Description
Added fundamental of programming

Fixes #526 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-14 16:42 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Arrays.md
> +# Arrays in C
This is not a good format based on our documentation style. You need to include basic information at the top of the page, such as the document ID (unique for URL), title, sidebar label, and position. You should also include tags for SEO and best practices.

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Conditionals.md
> +# Conditionals in C
same mistake

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Conditionals.md
> +- > : Greater than
replace `>` with `&gt;`

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Conditionals.md
> +- < : Less than
replace `<` with `&lt;`

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Conditionals.md
> +- <= : Less than or equal to
and also, replace `<`, and `>` because our site docs is based on mdx OR markdown + React

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Data Stuctures.md
> +# Data Structures in C
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Functions.md
> +# Functions in C
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Loops.md
> +# Loops in C
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-14 16:42 UTC, ajay-dhangar commented on docs/programming-fundamentals/Variables.md
> +# Variables in C
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-20 10:51 UTC, AbhijitMotekar99 commented
Hey @ajay-dhangar 
I updated my files in format

2024-10-21 00:35 UTC, ajay-dhangar requested changes
don't delete `docs/programming-fundamentals/_category_.json` file

2024-10-23 08:50 UTC, closed without merging