Add advanced data structure and some mathematical algorithms; included Java in A* implementation.
Ajay-Dhangar/algo pull request #682
Opened 2024-10-13 18:52 UTC by Lighting-pixel

## 📥 Pull Request

### Description
This pull request adds advanced data structures and algorithms, implements several mathematical algorithms, and includes Java code along with time and space complexity for the A* search algorithm. These enhancements aim to improve the project's coverage of important algorithms and provide clearer implementations for better understanding.

Fixes #602 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-15 00:45 UTC, Lighting-pixel commented
could you pls check @ajay-dhangar and if possible give me level2 label

2024-10-15 13:53 UTC, ajay-dhangar requested changes
Your content is very good. However, based on our suggestions, you need to correct a few mistakes.

2024-10-15 13:53 UTC, ajay-dhangar commented on docs/mathematics-algorithms/sieve-of-eratosthenes.md
> +
replace `\( n \)` with `$n$`, `\( p = 2 \)` with `$p=2$`, `\( p^2 \)` with `$ p^2$`, and `\( p \)` with `$p$`

2024-10-15 13:53 UTC, ajay-dhangar commented on docs/mathematics-algorithms/sieve-of-eratosthenes.md
> +
You need to check out https://docusaurus.io/docs/markdown-features/math-equations for more details on using math equations in our documentation.

2024-10-15 13:53 UTC, ajay-dhangar commented on docs/mathematics-algorithms/sieve-of-eratosthenes.md
> +- The space complexity is \( O(n) \) due to the array used to mark the prime numbers.
also, replace `\( O(n) \)` with `$O(n)$`

2024-10-15 16:26 UTC, Lighting-pixel commented
made the changes according to your suggestions pls review it and also assign me level 2 label in the issue as well @ajay-dhangar

2024-10-16 17:02 UTC, ajay-dhangar approved these changes
Done

2024-10-16 17:03 UTC, merged