Added algorithm for [Gray Code Algorithm Via Recursion ]
Ajay-Dhangar/algo pull request #690
Opened 2024-10-14 05:56 UTC by MithanshuHedau

## 📥 Pull Request

### Description
### Name : Gray Code Genaration 
Gray code is a binary numeral system where two successive values differ in only one bit. This unique property minimizes the chances of errors during transitions, making Gray code particularly useful in various applications, including digital communication, error correction, and mechanical encoders.

The process of generating Gray codes involves constructing a sequence of binary values that satisfy this property. The Gray code for n bits can be generated using a recursive method or a direct calculation approach, allowing for efficient computation even for larger values of n.

Problem Definition:
The goal of this algorithm is to generate a sequence of Gray codes for a given integer n, where 𝑛 is the number of bits. The output should consist of 2^𝑛 binary strings, each differing from the next by a single bit.

Input:
An integer 𝑛 (1 ≤ 𝑛≤ 16) representing the number of bits.

Output:
A list of 2^n Gray codes, each represented as a binary string of length 𝑛.

Examples:
Input: 𝑛=3
Output: : 
000
001
011
010
110
111
101
100

Algorithm Overview:
1 . Base Case: For 𝑛=0 return an array with a single empty string.
2 . Recursive Case:
     Generate the Gray codes for n−1 bits.
     Prepend '0' to each of these codes to form the first half of the sequence.
     Reverse the previous codes and prepend '1' to each to form the second half.

Detailed Steps:
1.  Calculate the total number of codes to generate: 2^n
2.  Iterate through the numbers from 0 to 2^n −1.
3 . For each number i, compute the corresponding Gray code using the formula:
     Gray(i)=i⊕(i>>1)
4 . Convert the result to a binary string, ensuring it has a length of n bits

Time Complexity:
    The time complexity of this algorithm isO(2^n), where n is the number of bits. Each code is computed in constant time, 
     resulting in a linear relationship with respect to the total number of codes generated .

Limitations:
    The maximum value of n is generally limited to 16 due to the exponential growth of the output size and potential memory 
    constraints. Beyond this, the performance may degrade.

Applications:
     Gray codes are widely used in digital electronics, especially in applications where the precision of transitions is critical, such 
     as:
          1. Analog to Digital Converters (ADC)
          2. Robotics and motion control systems
          3. Error detection and correction in digital communication

### Type of change
- [✔️ ] New feature (non-breaking change which adds functionality)
- [ ✔️] Documentation update

### Checklist:

- [✔️ ] My code follows the style guidelines of this project
- [✔️ ] I have performed a self-review of my code
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
- [✔️ ] I have added tests that prove my fix is effective or that my feature works
- [✔️ ] New and existing unit tests pass locally with my changes
- [ ✔️] Any dependent changes have been merged and published in downstream modules

2024-10-15 15:18 UTC, MithanshuHedau commented
@ajay-dhangar , Can you please check this pull request and merge it ,  if it is all ok

2024-10-15 17:15 UTC, ajay-dhangar requested changes
update code based on suggestions and solve errors

2024-10-15 17:15 UTC, ajay-dhangar commented on docs/Recursion/GrayCodeGeneration.md
> +title:Gray Code Generation Using Recursion
replace `title:Gray Code Generation Using Recursion` with `title: Gray Code Generation Using Recursion` because you need space between

2024-10-15 17:15 UTC, ajay-dhangar commented on docs/Recursion/GrayCodeGeneration.md
> +* An integer n (1 ≤ n ≤ 16) representing the number of bits for which the Gray code needs to be generated.
replace `(1 ≤ n ≤ 16)` with ``` `(1 ≤ n ≤ 16)` ```

2024-10-15 17:26 UTC, MithanshuHedau commented
@ajay-dhangar , I did Changes ; Please check it now ,,,,if it is now Okay  or not

2024-10-16 02:26 UTC, MithanshuHedau commented
@ajay-dhangar , can you please check it now , if it is all okay then can you please merge it into the main

2024-10-16 17:21 UTC, ajay-dhangar approved these changes
Done

2024-10-16 17:21 UTC, merged