Added Java to Language section
Ajay-Dhangar/algo pull request #694
Opened 2024-10-14 07:46 UTC by LitZeus

## 📥 Pull Request

### Description
The Java programming language has been added to the `Languages` section
Fixes #527 

![image](https://github.com/user-attachments/assets/5cbe90e3-ca58-407c-8f56-b3fb1bc5c1f1)

<br />

![image](https://github.com/user-attachments/assets/2b0e483c-7dea-44b1-98c0-9bcbc389ba60)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-15 16:38 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-15 16:38 UTC, ajay-dhangar commented on docs/languages/java/java-2.md
> +| \<= | Less than or equal to | x \<= y |
replace `<` with `&lt;`, and `>` with `&gt;`

2024-10-15 16:38 UTC, ajay-dhangar commented on docs/languages/java/java-2.md
> +| ! | Logical NOT | !(x \> 5) |
The HTML code you provided is using `<` and `>` to create tags. This is causing a conflict with the JavaScript syntax for JSX in React.js, which also uses `<` and `>` to create tags. To resolve this conflict, you can replace the `<` and `>` characters in the HTML or .md code with their HTML entity equivalents, `&lt;` and `&gt;`.

2024-10-15 16:38 UTC, ajay-dhangar commented on docs/languages/java/java-2.md
> +
also, replace `>`, and `<`

2024-10-15 17:24 UTC, LitZeus commented
@ajay-dhangar I have done the changes, shall I make another PR for this?

I have also made the changes in the codes in the CLI as they were coming in the single line.

2024-10-15 18:14 UTC, LitZeus commented
@ajay-dhangar When i pulled the main branch to make changes by having the latest repo version i am getting this error!
Though I have made the changes as per you have told.
Please have a look!

![image](https://github.com/user-attachments/assets/63701557-deb4-4d2c-957f-518639642415)

2024-10-16 17:09 UTC, ajay-dhangar commented
> @ajay-dhangar When i pulled the main branch to make changes by having the latest repo version i am getting this error! Though I have made the changes as per you have told. Please have a look!
> 
> ![image](https://private-user-images.githubusercontent.com/142726372/376737729-63701557-deb4-4d2c-957f-518639642415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTMyNTMsIm5iZiI6MTcyOTA5Mjk1MywicGF0aCI6Ii8xNDI3MjYzNzIvMzc2NzM3NzI5LTYzNzAxNTU3LWRlYjQtNGQyYy05NTdmLTUxODYzOTY0MjQxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTM1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTE2ZmU3MmY5NGRiZGRjZDQ3OWY3NDIzYmU4ODBhNjUwNTY4ZTJlZTM3YTU5ZDc4NWU3NTZiNTU0NTcyMzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.blu674mN8xI0IVCEbpuFA3Edo0dWhMup3lnWVAjEA6M)

If you get this error, you need to run the command `npm i` to install our React Lite YouTube Embed (a new package for video content).

2024-10-16 17:12 UTC, ajay-dhangar approved these changes
Done || I'll fix `.md` syntax error

2024-10-16 17:15 UTC, merged