Added all the algorithms of trees data structure
Ajay-Dhangar/algo pull request #704
Opened 2024-10-14 12:51 UTC by karanmaheshwari16

## 📥 Pull Request

### Description
I have added all the basic an most used algorithms used in the trees data structure in data structures and algorithms.
They are written in format simple to understand and have no bugs and work perfectly.

Fixes # (663)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-15 12:54 UTC, karanmaheshwari16 commented
@ajay-dhangar please review this pull request

2024-10-15 14:23 UTC, ajay-dhangar requested changes
We only need the `.md` file for our documentation. Please delete the other files. like `.cpp`

2024-10-15 17:22 UTC, karanmaheshwari16 commented
> We only need the `.md` file for our documentation. Please delete the other files. like `.cpp`

sir these are the c++ files that represent the code.
Should i add a .md file in the current dir for the documentation?

otherwise all i have is the .cpp files for the code

2024-10-16 17:18 UTC, ajay-dhangar commented
> > We only need the `.md` file for our documentation. Please delete the other files. like `.cpp`
> 
> sir these are the c++ files that represent the code. Should i add a .md file in the current dir for the documentation?
> 
> otherwise all i have is the .cpp files for the code

Only write code in `.md` file and delete all `.cpp` files

2024-10-18 04:17 UTC, karanmaheshwari16 commented
Done Sir 
Deleted all the .cpp files and integrated all the code in .md file

2024-10-18 04:28 UTC, ajay-dhangar requested changes
Update code based on suggestions

2024-10-18 04:28 UTC, ajay-dhangar commented on trees/tree.md
> +# Tree Algorithms in C++
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-18 19:10 UTC, karanmaheshwari16 commented
Done Sir

2024-10-19 04:39 UTC, ajay-dhangar requested changes
you write your file in wrong place like `trees/tree.md` but we need in `docs` folder so, can you write in docs folder

2024-10-19 05:18 UTC, karanmaheshwari16 commented
done👍

2024-10-19 14:50 UTC, ajay-dhangar approved these changes
Done

2024-10-19 14:52 UTC, merged