solved #705 created greedy  leetcode solutions
Ajay-Dhangar/algo pull request #706
Opened 2024-10-14 14:21 UTC by KapuluruBhuvaneswariVspdbct

## 📥 Pull Request

### Description
solved #705 created greedy  leetcode solutions
Fixes #705 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-14 14:53 UTC, ajay-dhangar requested changes
Please don't edit the `src/pages/Quizes/stack.tsx` and `src/pages/Quizes/quiz.css` files.

2024-10-14 15:00 UTC, KapuluruBhuvaneswariVspdbct reviewed
removed changes stack,quiz

2024-10-14 15:05 UTC, KapuluruBhuvaneswariVspdbct commented
now please merge it

2024-10-14 15:06 UTC, KapuluruBhuvaneswariVspdbct commented
sir please merge this and kindly give label level2 or level3

2024-10-15 10:43 UTC, KapuluruBhuvaneswariVspdbct commented
sir conflicts are resolved could you please merge it sir

2024-10-15 13:01 UTC, ajay-dhangar requested changes
Before you push your code, please update it based on the suggestions I've provided. Also, please recheck your code before pushing it.

2024-10-15 13:01 UTC, ajay-dhangar commented on docs/leetcode Solutions/greedy-leetcode-solutions.md
> +</main>
why use `</main>`

2024-10-15 13:01 UTC, ajay-dhangar commented on docs/leetcode Solutions/greedy-leetcode-solutions.md
> +<k>
why use `<k>`

2024-10-15 13:01 UTC, ajay-dhangar commented on docs/leetcode Solutions/greedy-leetcode-solutions.md
> +</main>
Can you explain why `</main>` is used here? If you need to use it, do you need to follow `.mdx` or `jsx` syntax?

2024-10-15 13:04 UTC, KapuluruBhuvaneswariVspdbct commented
Asking for resolve conflict

On Tue, Oct 15, 2024, 6:32 PM Ajay Dhangar ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Before you push your code, please update it based on the suggestions I've
> provided. Also, please recheck your code before pushing it.
> ------------------------------
>
> In docs/leetcode Solutions/greedy-leetcode-solutions.md
> <https://github.com/ajay-dhangar/algo/pull/706#discussion_r1801120288>:
>
> >  # Greedy-LeetCode Solutions 1-5
> +</main>
>
> why use </main>
> ------------------------------
>
> In docs/leetcode Solutions/greedy-leetcode-solutions.md
> <https://github.com/ajay-dhangar/algo/pull/706#discussion_r1801120748>:
>
> > @@ -7,14 +7,26 @@ description: "This document contains solutions to LeetCode DSA problems 1-10 con
>  tags: [leetcode, algorithms, problem-solving, DSA, data structure]
>  ---
>
> +<k>
>
> why use <k>
> ------------------------------
>
> In docs/leetcode Solutions/greedy-leetcode-solutions.md
> <https://github.com/ajay-dhangar/algo/pull/706#discussion_r1801123264>:
>
> >
>  ## Questions
>  1. [The Two Sneaky Numbers of Digitville](#1-the-two-sneaky-numbers-of-digitville)
>  2. [Design Neighbor Sum Service](#2-design-neighbor-sum-service)
>  3. [Find the Number of Winning Players](#3-find-the-number-of-winning-players)
>  4. [Count Pairs That Form a Complete Day I](#4-count-pairs-that-form-a-complete-day-i)
>  5. [Remove Element](#5-remove-element)
> +<k>
> +6. [Remove Duplicates from Sorted Array](#6-remove-duplicates-from-sorted-array)
> +7. [Merge Two Sorted Lists](#7-merge-two-sorted-lists)
> +8. [Generate Parentheses](#8-generate-parentheses)
> +9. [Merge k Sorted Lists](#9-merge-k-sorted-lists)
> +10. [Swap Nodes in Pairs](#10-swap-nodes-in-pairs)
> +=======
> +</main>
>
> Can you explain why </main> is used here? If you need to use it, do you
> need to follow .mdx or jsx syntax?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ajay-dhangar/algo/pull/706#pullrequestreview-2369266929>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BHOWNHGC2KC5XSL2OJ3X343Z3UG5PAVCNFSM6AAAAABP5D47VKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRZGI3DMOJSHE>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-10-20 15:02 UTC, KapuluruBhuvaneswariVspdbct reviewed
removed conflicts

2024-10-21 00:32 UTC, closed without merging