Balanced bin tree
Ajay-Dhangar/algo pull request #760
Opened 2024-10-15 08:05 UTC by Rashigera

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
added program in java and python to check if a tree is balanced or not . its a important concept and is asked in interviews a lot of time by many companies

Fixes # (issue number) #430 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [T ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ T] My code follows the style guidelines of this project
- [ T] I have performed a self-review of my code
- [ T] I have commented my code, particularly in hard-to-understand areas
- [ T] I have added tests that prove my fix is effective or that my feature works
- [ T] New and existing unit tests pass locally with my changes
- [T ] Any dependent changes have been merged and published in downstream modules

2024-10-15 10:28 UTC, ajay-dhangar requested changes
We need only `.md` files for our documentation. If you have written your code in another file format, please convert it to `.md` format.

2024-10-15 10:57 UTC, Rashigera commented
added only .md files.

2024-10-16 11:26 UTC, ajay-dhangar requested changes
Please delete the .java and .py files. For the .md file, please read our guide at https://github.com/ajay-dhangar/algo?tab=readme-ov-file#resources-for-guidance.

2024-10-16 11:27 UTC, ajay-dhangar commented
> Please delete the .java and .py files. For the .md file, please read our guide at https://github.com/ajay-dhangar/algo?tab=readme-ov-file#resources-for-guidance.

## Resources for Guidance
Here are some resources that may be helpful as you contribute to Algo:
- [Docusaurus Documentation](https://docusaurus.io/docs/docs-introduction)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

2024-10-16 13:07 UTC, Rashigera commented
@ajay-dhangar  the correction is done , kindly check and let me know

2024-10-16 17:26 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-16 17:26 UTC, ajay-dhangar commented on docs/balancedBinTree/balancedBinTreejava.md
> +# Balanced Binary Tree Checker
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-16 17:26 UTC, ajay-dhangar commented on docs/balancedBinTree/balancedBinTreejava.md
> +}
And please close your code snippets with ```` ``` ````

2024-10-18 11:17 UTC, Rashigera commented
@ajay-dhangar I have made the necessary changes. kindly check and let me know if anymore update or correction is required

2024-10-18 15:31 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-18 15:31 UTC, ajay-dhangar commented on docs/balancedBinTree/balancedBinTree.md
> +sidebar_label: 4. Balanced Binary Tree (Python)
replace `sidebar_label: 4. Balanced Binary Tree (Python)` with `sidebar_label: "Balanced Binary Tree (Python)"`

2024-10-18 15:31 UTC, ajay-dhangar commented on docs/balancedBinTree/balancedBinTree.md
> +    print("The tree is not balanced.")
close your example with ```` ``` ````

2024-10-18 15:31 UTC, ajay-dhangar commented on docs/balancedBinTree/balancedBinTreejava.md
> +sidebar_label: 110. Balanced Binary Tree
replace `sidebar_label: 110. Balanced Binary Tree` with `sidebar_label: Balanced Binary Tree`

2024-10-18 15:31 UTC, ajay-dhangar commented on docs/balancedBinTree/balancedBinTreejava.md
> +
you can try 

replace 

```md
> A binary tree in which the left and right subtrees of every node differ in height by no more than one.
```
with 

```md
:::note
A binary tree in which the left and right subtrees of every node differ in height by no more than one.
:::
```

2024-10-19 04:40 UTC, ajay-dhangar approved these changes
Done

2024-10-19 04:40 UTC, merged