Create Matrix Data Structure
Ajay-Dhangar/algo pull request #776
Opened 2024-10-15 15:19 UTC by Mahateaa

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

### Type of change

- [.] Bug fix (non-breaking change which fixes an issue)
- [.] New feature (non-breaking change which adds functionality)
- [.] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [.] Documentation update

### Checklist:

- [.] My code follows the style guidelines of this project
- [.] I have performed a self-review of my code
- [.] I have commented my code, particularly in hard-to-understand areas
- [.] I have added tests that prove my fix is effective or that my feature works
- [.] New and existing unit tests pass locally with my changes
- [.] Any dependent changes have been merged and published in downstream modules

2024-10-16 17:41 UTC, Mahateaa commented
@ajay-dhangar #719 can you please verify this PR

2024-10-17 05:29 UTC, ajay-dhangar requested changes
Update your code based on suggestions and when you're done editing your code, save your file with a `.md` extension.

2024-10-17 05:29 UTC, ajay-dhangar commented on docs/basic-dsa/Matrix Data Structure
> +   \[
replace 
```md
  \[
   (A^T)[i][j] = A[j][i]
   \]
```

with
```md
 $$
   (A^T)[i][j] = A[j][i]
  $$
```

2024-10-17 05:29 UTC, ajay-dhangar commented on docs/basic-dsa/Matrix Data Structure
> +
replace

```md
\[
   C[i][j] = \sum_{k=1}^{n} A[i][k] \times B[k][j]
 \]
```

with

```md
$$
   C[i][j] = '\sum_{k=1}^{n} A[i][k] \times B[k][j]'
$$
```

2024-10-17 05:29 UTC, ajay-dhangar commented on docs/basic-dsa/Matrix Data Structure
> +
replace 

```md
\[
   C[i][j] = A[i][j] - B[i][j]
   \]
```

with
```md
$$
   C[i][j] = A[i][j] - B[i][j]
$$
```

2024-10-17 05:29 UTC, ajay-dhangar commented on docs/basic-dsa/Matrix Data Structure
> +
replace

```md
   \[
   C[i][j] = A[i][j] + B[i][j]
   \]
```

with
```md
  $$
   C[i][j] = A[i][j] + B[i][j]
  $$
```

2024-10-17 05:29 UTC, ajay-dhangar commented on docs/basic-dsa/Matrix Data Structure
> +
add ```` ``` ```` in line number 29 because you need to close your example

2024-10-17 05:29 UTC, ajay-dhangar commented on docs/basic-dsa/Matrix Data Structure
> +# Matrix Data Structure
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-17 15:48 UTC, Mahateaa commented
done @ajay-dhangar can you please check now?

2024-10-18 08:34 UTC, ajay-dhangar approved these changes
Done

2024-10-18 08:38 UTC, merged