Add Fruit_Into_Baskets Implementation
Ajay-Dhangar/algo pull request #831
Opened 2024-10-16 07:52 UTC by Mahak-Codes

## 🚀 Pull Request

### Description
This pull request implements the "Fruit into Basket" problem. The task is to collect the maximum number of fruits in two baskets, where each basket can hold only one type of fruit at a time. The goal is to find the longest subarray that contains at most two distinct types of fruits.

Fixes # 826

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-10-17 10:21 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-17 10:21 UTC, ajay-dhangar commented on docs/leetcode Solutions/Fruit_Into_Baskets.md
> +# Fruit Into Baskets ( Leetcode-904)
We need on top

```md
---
id: ___
title: ___
sidebar_label: ___
sidebar_position: ___
description: ___
tags: [___, __, ]
---
```

### Detailed Guidelines

- id: Unique identifier for the route.
- title: Title of the problem.
- sidebar_label: Problem number or label for the sidebar.
- tags: Relevant tags for the problem.
- description: A short SEO-friendly description. No HTML tags.

2024-10-17 10:21 UTC, ajay-dhangar commented on docs/leetcode Solutions/Fruit_Into_Baskets.md
> +}
please close your code example with  ```` ``` ````

2024-10-17 16:47 UTC, Mahak-Codes commented
@ajay-dhangar I successfully update my code based on suggestions. Can you please review again.

2024-10-18 08:40 UTC, ajay-dhangar approved these changes
Done

2024-10-18 08:40 UTC, merged