Program to find letter with highest frequency in a string in Java,C++,Python.
Ajay-Dhangar/algo pull request #838
Opened 2024-10-16 09:21 UTC by riyaa060

## 📥 Pull Request

### Description
I have added a markdown document which find letter with highest frequency in string.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-16 14:29 UTC, ajay-dhangar requested changes
update your code based on suggestions and can't edit `docs/basic-dsa/Strings/Reversing a string.md` file because this file already merged

2024-10-16 14:29 UTC, ajay-dhangar commented on docs/basic-dsa/Strings/Highest freqyuency letter.md
> +- for (char letter : frequency.keySet()) { ... }: This loop iterates over the keys (letters) in the frequency map.
replace `(char letter : frequency.keySet()) { ... }` with ``` `(char letter : frequency.keySet()) { ... }` ```

2024-10-16 14:29 UTC, ajay-dhangar commented on docs/basic-dsa/Strings/Highest freqyuency letter.md
> +- if (frequency.get(letter) > highestCount) { ... }: Inside the loop, this condition checks if the current letter’s frequency is greater than highestCount. If so, it updates highestCount and sets hig
replace `(frequency.get(letter) > highestCount) { ... }` with ``` `(frequency.get(letter) > highestCount) { ... }` ```

2024-10-17 10:48 UTC, ajay-dhangar approved these changes
Done

2024-10-17 10:49 UTC, merged

2024-10-17 11:12 UTC, riyaa060 commented
Could you please add **hacktoberfest2024** and **hacktoberfest-accepted** labels too? @ajay-dhangar