Binary Tree Intro
Ajay-Dhangar/algo pull request #84
Opened 2024-10-05 16:48 UTC by KhawajaFashi

## 📥 Pull Request: Introduction to Binary Trees

### Description
This pull request introduces an Introduction to Binary Trees section, covering the basic concepts, properties, types, and advantages/disadvantages of binary trees. This content is aimed to enhance the documentation and provide readers with foundational knowledge about binary trees. The section explains:

- Definition and structure of binary trees (nodes, edges).
- Key properties (height, depth, balance).
- Different types of binary trees (Full, Complete, Perfect, Balanced, Degenerate).
- Advantages and disadvantages.

Fixes #78 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2024-10-05 17:30 UTC, ajay-dhangar requested changes
@KhawajaFashi Your code needs to be updated based on the suggestions provided in the comments. Please let me know if you have any questions.

2024-10-05 17:30 UTC, ajay-dhangar commented on docs/Binary Trees/binary-tree.md
> +    <pre>         A
replace

```md
    <pre>
           A
         /   \
        B     C
       /     / \
      D     F   G
    </pre>
```

with

````md
```
          A
         /   \
        B     C
       /     / \
      D     F   G
```
````

2024-10-05 17:30 UTC, ajay-dhangar commented on docs/Binary Trees/binary-tree.md
> +    <pre>      A
replace `<pre>` with ```` ``` ```` (following  .md / .mdx syntex )

2024-10-05 17:46 UTC, KhawajaFashi commented on docs/Binary Trees/binary-tree.md
> +    <pre>      A
Ok sir I will change it accordingly

2024-10-06 03:15 UTC, ajay-dhangar approved these changes
Done

2024-10-06 03:15 UTC, merged