Feature: C language under languages section
Ajay-Dhangar/algo pull request #842
Opened 2024-10-16 12:10 UTC by ishita-1305

## 📥 Pull Request

### Description
Added introduction to C, its data types, operators, decision-making, loop codes in the C folder under the languages section.

Fixes : #639 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-16 13:34 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-16 13:34 UTC, ajay-dhangar commented on docs/languages/C/c-2.md
> +| \<=      | Less than or equal to    | x \<= y |
replace `<` with `&lt;` and `>` with `&gt;`

2024-10-16 13:34 UTC, ajay-dhangar commented on docs/languages/C/c-2.md
> +| !        | Logical NOT | !(x \> 5)           |
also, replace `<` and `>` because it's also introducing as a tags syntax

2024-10-16 17:39 UTC, ishita-1305 commented
@ajay-dhangar please review the changes

2024-10-17 10:53 UTC, ajay-dhangar approved these changes
Done

2024-10-17 10:53 UTC, merged