Added question in array folder Maximum_Sum_sub_squre_matrix
Ajay-Dhangar/algo pull request #883
Opened 2024-10-17 11:29 UTC by khurshed07

issue #845

## 📥 Pull Request

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (#845)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Implementation of MAXIMUM SUM OF SUB-SQUARE MATRIX for Issue #845

## Description
This pull request addresses Issue #845 by implementing the solution to the problem of finding the maximum sum of a k x k sub-square matrix within a given n x n matrix. The objective is to efficiently compute the sum of all possible k x k sub-squares and identify the one with the highest sum.

## Approach
The solution is implemented using a two-step approach:

1. **Preprocessing Strip Sums:** The algorithm calculates the sums of all strips of size k x 1 for each column in the matrix. This preprocessing step allows for efficient computation of k x k sub-square sums.

2. **Sum Calculation of Sub-squares:** Using the precomputed strip sums, the algorithm calculates the sum of each k x k sub-square and updates the maximum sum found.

## Algorithm
- **Construct Strip Sums:** An auxiliary array is created to store the sums of strips of size k x 1 for each column.
- **Calculate Sum of Sub-squares:** Iterate over the matrix to compute the sums of all k x k sub-squares using the precomputed strip sums.
- **Update Maximum Sum:** Keep track of the maximum sum and its position in the matrix.

## Code Explanation
- **printMaxSumSub Function:** The main function where the logic for finding the maximum sum sub-square matrix is implemented. It handles preprocessing and computes the maximum sum of the k x k sub-square.
- **Matrix Declaration and Driver Code:** The driver code demonstrates how to use the function with an example matrix.

## Files Added
- **Max_Sum_Sub_Square_Matrix.md:** Contains the problem statement, solution explanation, and steps to run the program.
- **Max_Sum_Sub_Square_Matrix.cpp:** The C++ program implementing the algorithm to solve the problem.

### The file has been placed in the Array folder.

---

Thank you for your time and consideration!

Best regards,  
@khurshed07  
[GitHub Profile](https://github.com/khurshed07)

2024-10-18 15:57 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-18 15:57 UTC, ajay-dhangar commented on arrays/Maximum Sum Sub-square Matrix.md
> +}
close your example with ```` ``` ````

2024-10-18 16:59 UTC, khurshed07 commented
Hi @ajay-dhangar,

I have closed the example with ``` as required. Could you please check it and submit the pull request? If there are any issues, feel free to let me know.

Thank you!

@khurshed07 khurshed

2024-10-19 04:23 UTC, ajay-dhangar approved these changes
Done

2024-10-19 04:27 UTC, merged