Implement GitHub PR Issue Checker Workflow
Ajay-Dhangar/algo pull request #943
Opened 2024-10-18 01:18 UTC by smog-root

**Fixes:** #900 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes #<issue-number>` or `Fixes #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

2024-10-18 04:46 UTC, ajay-dhangar requested changes
Thank you for your pull request. Please make only one line change, and then I will merge it.

2024-10-18 04:46 UTC, ajay-dhangar commented on .github/workflows/pr-checker.yml
> +            echo "##[error]Fixes #NEW must be included in the description."
replace `#NEW` with `#ISSUE_NUMBER`

2024-10-18 04:49 UTC, smog-root commented on .github/workflows/pr-checker.yml
> +            echo "##[error]Fixes #NEW must be included in the description."
Done 👍!

2024-10-18 09:03 UTC, smog-root commented
i have updated the changes! merge it! @ajay-dhangar

2024-10-18 12:30 UTC, smog-root commented
hey @ajay-dhangar in the issue #900 .You added level2 label. 
But now in the PR you added level1! please don't do that

2024-10-19 04:57 UTC, ajay-dhangar approved these changes
Done

2024-10-19 04:59 UTC, merged

2024-10-19 05:06 UTC, smog-root commented
Add hacktoberfest-accepted label! @ajay-dhangar