Add files via upload
Ajay-Dhangar/algo pull request #995
Opened 2024-10-19 08:11 UTC by KashishJuneja101003

## 📥 Pull Request

### Description
I have added 27 GFG problems along with their solutions in cpp.

Fixes #775 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-20 03:26 UTC, ajay-dhangar requested changes
update your code based on suggestions

2024-10-20 03:26 UTC, ajay-dhangar commented on docs/gfg solutions.md
> +**Description:** Given an expression string x. Examine whether the pairs and the orders of {,},(,),[,] are correct in exp. For example, the function should return 'true' for exp = [()]{}{[()()]()} an
replace `{,},(,),[,]` with ``` `{,},(,),[,]` ```

2024-10-20 03:26 UTC, ajay-dhangar commented on docs/gfg solutions.md
> +**Description:** Given an expression string x. Examine whether the pairs and the orders of {,},(,),[,] are correct in exp. For example, the function should return 'true' for exp = [()]{}{[()()]()} an
and `[()]{}{[()()]()}` with ``` `[()]{}{[()()]()}` ```

2024-10-20 04:40 UTC, KashishJuneja101003 commented
Kindly add hacktoberfest-accepted label also.
Thank You!

2024-10-21 00:29 UTC, ajay-dhangar approved these changes
Done

2024-10-21 00:29 UTC, merged